<!-- HTML header for doxygen 1.8.20-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<!-- Mirrored from www.open3d.org/docs/release/cpp_api/_continuous_conv_c_u_d_a_kernels_8h_source.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 14 May 2023 11:04:55 GMT -->
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Open3D (C++ API): /home/runner/work/Open3D/Open3D/cpp/open3d/ml/impl/continuous_conv/ContinuousConvCUDAKernels.h (9238339 (Tue Mar 14 18:49:09 2023 -0700)) Source File</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    extensions: ["tex2jax.js", "TeX/AMSmath.html", "TeX/AMSsymbols.js"],
    jax: ["input/TeX","output/HTML-CSS"],
});
</script>
<script type="text/javascript" async="async" src="../../../../cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-3TQPKGV6Z3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-3TQPKGV6Z3');
</script>
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectlogo"><img alt="Logo" src="open3d_logo.ico"/></td>
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Open3D (C++ API)
   &#160;<span id="projectnumber">0.17.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.html');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.html','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_df511e5bd85cec96854b39d5e1c27aa8.357.del">cpp</a></li><li class="navelem"><a class="el" href="dir_f8cc15b2217ff526bd336cf17635da2a.358.del">open3d</a></li><li class="navelem"><a class="el" href="dir_b383250e6a9804e003b118f7109c729e.4d9.del">ml</a></li><li class="navelem"><a class="el" href="dir_d2402e7861dbbf5555a99e031eda3ca3.8e8.del">impl</a></li><li class="navelem"><a class="el" href="dir_4b58b113595680d998266bc1fc8ab010.c11.del">continuous_conv</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">ContinuousConvCUDAKernels.h</div>  </div>
</div><!--header-->
<div class="contents">
<a href="_continuous_conv_c_u_d_a_kernels_8h.cc6.dela">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;<span class="comment">// ----------------------------------------------------------------------------</span></div>
<div class="line"><a name="l00002"></a><span class="lineno">    2</span>&#160;<span class="comment">// -                        Open3D: www.open3d.org                            -</span></div>
<div class="line"><a name="l00003"></a><span class="lineno">    3</span>&#160;<span class="comment">// ----------------------------------------------------------------------------</span></div>
<div class="line"><a name="l00004"></a><span class="lineno">    4</span>&#160;<span class="comment">// Copyright (c) 2018-2023 www.open3d.org</span></div>
<div class="line"><a name="l00005"></a><span class="lineno">    5</span>&#160;<span class="comment">// SPDX-License-Identifier: MIT</span></div>
<div class="line"><a name="l00006"></a><span class="lineno">    6</span>&#160;<span class="comment">// ----------------------------------------------------------------------------</span></div>
<div class="line"><a name="l00007"></a><span class="lineno">    7</span>&#160; </div>
<div class="line"><a name="l00008"></a><span class="lineno">    8</span>&#160;<span class="preprocessor">#pragma once</span></div>
<div class="line"><a name="l00009"></a><span class="lineno">    9</span>&#160; </div>
<div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="preprocessor">#include &lt;vector&gt;</span></div>
<div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160; </div>
<div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="_coordinate_transformation_8cuh.html">open3d/ml/impl/continuous_conv/CoordinateTransformation.cuh</a>&quot;</span></div>
<div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160; </div>
<div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="keyword">namespace </span><a class="code" href="namespaceopen3d.html">open3d</a> {</div>
<div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160;<span class="keyword">namespace </span>ml {</div>
<div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;<span class="keyword">namespace </span>impl {</div>
<div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160; </div>
<div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;<span class="keyword">template</span> &lt;<span class="keyword">class</span> TFeat, <span class="keyword">class</span> TReal, <span class="keyword">class</span> TIndex&gt;</div>
<div class="line"><a name="l00097"></a><span class="lineno"><a class="line" href="namespaceopen3d_1_1ml_1_1impl.html#afac64bdddd123dfede9328296c820553">   97</a></span>&#160;<span class="keywordtype">void</span> <a class="code" href="namespaceopen3d_1_1ml_1_1impl.html#afac64bdddd123dfede9328296c820553">FillColumn</a>(<span class="keyword">const</span> cudaStream_t&amp; stream,</div>
<div class="line"><a name="l00098"></a><span class="lineno">   98</span>&#160;                TFeat* columns,</div>
<div class="line"><a name="l00099"></a><span class="lineno">   99</span>&#160;                <span class="keywordtype">int</span> in_channels,</div>
<div class="line"><a name="l00100"></a><span class="lineno">  100</span>&#160;                TIndex begin_idx,</div>
<div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;                TIndex end_idx,</div>
<div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;                TIndex num_out,</div>
<div class="line"><a name="l00103"></a><span class="lineno">  103</span>&#160;                <span class="keyword">const</span> TReal* <span class="keyword">const</span> __restrict__ out_positions,</div>
<div class="line"><a name="l00104"></a><span class="lineno">  104</span>&#160;                TIndex num_inp,</div>
<div class="line"><a name="l00105"></a><span class="lineno">  105</span>&#160;                <span class="keyword">const</span> TReal* <span class="keyword">const</span> __restrict__ inp_positions,</div>
<div class="line"><a name="l00106"></a><span class="lineno">  106</span>&#160;                <span class="keyword">const</span> TFeat* <span class="keyword">const</span> __restrict__ inp_features,</div>
<div class="line"><a name="l00107"></a><span class="lineno">  107</span>&#160;                <span class="keyword">const</span> TFeat* <span class="keyword">const</span> __restrict__ inp_importance,</div>
<div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;                <span class="keywordtype">size_t</span> neighbors_index_size,</div>
<div class="line"><a name="l00109"></a><span class="lineno">  109</span>&#160;                <span class="keyword">const</span> TIndex* <span class="keyword">const</span> __restrict__ neighbors_index,</div>
<div class="line"><a name="l00110"></a><span class="lineno">  110</span>&#160;                <span class="keyword">const</span> TFeat* <span class="keyword">const</span> __restrict__ neighbors_importance,</div>
<div class="line"><a name="l00111"></a><span class="lineno">  111</span>&#160;                <span class="keyword">const</span> int64_t* <span class="keyword">const</span> __restrict__ neighbors_row_splits,</div>
<div class="line"><a name="l00112"></a><span class="lineno">  112</span>&#160;                <span class="keyword">const</span> TReal* <span class="keyword">const</span> __restrict__ extents,</div>
<div class="line"><a name="l00113"></a><span class="lineno">  113</span>&#160;                <span class="keyword">const</span> TReal* <span class="keyword">const</span> __restrict__ offsets,</div>
<div class="line"><a name="l00114"></a><span class="lineno">  114</span>&#160;                <span class="keyword">const</span> std::vector&lt;int&gt;&amp; filter_dims,</div>
<div class="line"><a name="l00115"></a><span class="lineno">  115</span>&#160;                <a class="code" href="namespaceopen3d_1_1ml_1_1impl.html#a1cdea72ec606986b7ada2e619ea41a8d">InterpolationMode</a> interpolation,</div>
<div class="line"><a name="l00116"></a><span class="lineno">  116</span>&#160;                <a class="code" href="namespaceopen3d_1_1ml_1_1impl.html#ad39d07a9288168e9ecab8f34e24d27fb">CoordinateMapping</a> coordinate_mapping,</div>
<div class="line"><a name="l00117"></a><span class="lineno">  117</span>&#160;                <span class="keywordtype">bool</span> align_corners,</div>
<div class="line"><a name="l00118"></a><span class="lineno">  118</span>&#160;                <span class="keywordtype">bool</span> individual_extent,</div>
<div class="line"><a name="l00119"></a><span class="lineno">  119</span>&#160;                <span class="keywordtype">bool</span> isotropic_extent,</div>
<div class="line"><a name="l00120"></a><span class="lineno">  120</span>&#160;                <span class="keywordtype">bool</span> normalize);</div>
<div class="line"><a name="l00121"></a><span class="lineno">  121</span>&#160; </div>
<div class="line"><a name="l00122"></a><span class="lineno">  122</span>&#160;<span class="keyword">template</span> &lt;<span class="keyword">class</span> TFeat, <span class="keyword">class</span> TReal, <span class="keyword">class</span> TIndex&gt;</div>
<div class="line"><a name="l00123"></a><span class="lineno"><a class="line" href="namespaceopen3d_1_1ml_1_1impl.html#a915147ba8aa5ab252a532fa9823c9adb">  123</a></span>&#160;<span class="keywordtype">void</span> <a class="code" href="namespaceopen3d_1_1ml_1_1impl.html#a915147ba8aa5ab252a532fa9823c9adb">FillColumnTranspose</a>(</div>
<div class="line"><a name="l00124"></a><span class="lineno">  124</span>&#160;        <span class="keyword">const</span> cudaStream_t&amp; stream,</div>
<div class="line"><a name="l00125"></a><span class="lineno">  125</span>&#160;        TFeat* columns,</div>
<div class="line"><a name="l00126"></a><span class="lineno">  126</span>&#160;        <span class="keywordtype">int</span> in_channels,</div>
<div class="line"><a name="l00127"></a><span class="lineno">  127</span>&#160;        TIndex begin_idx,</div>
<div class="line"><a name="l00128"></a><span class="lineno">  128</span>&#160;        TIndex end_idx,</div>
<div class="line"><a name="l00129"></a><span class="lineno">  129</span>&#160;        TIndex num_out,</div>
<div class="line"><a name="l00130"></a><span class="lineno">  130</span>&#160;        <span class="keyword">const</span> TReal* <span class="keyword">const</span> __restrict__ out_positions,</div>
<div class="line"><a name="l00131"></a><span class="lineno">  131</span>&#160;        TIndex num_inp,</div>
<div class="line"><a name="l00132"></a><span class="lineno">  132</span>&#160;        <span class="keyword">const</span> TReal* <span class="keyword">const</span> __restrict__ inp_positions,</div>
<div class="line"><a name="l00133"></a><span class="lineno">  133</span>&#160;        <span class="keyword">const</span> TFeat* <span class="keyword">const</span> __restrict__ inp_features,</div>
<div class="line"><a name="l00134"></a><span class="lineno">  134</span>&#160;        <span class="keyword">const</span> TFeat* <span class="keyword">const</span> __restrict__ inp_neighbors_importance_sum,</div>
<div class="line"><a name="l00135"></a><span class="lineno">  135</span>&#160;        <span class="keyword">const</span> int64_t* <span class="keyword">const</span> __restrict__ inp_neighbors_prefix_sum,</div>
<div class="line"><a name="l00136"></a><span class="lineno">  136</span>&#160;        <span class="keywordtype">size_t</span> neighbors_index_size,</div>
<div class="line"><a name="l00137"></a><span class="lineno">  137</span>&#160;        <span class="keyword">const</span> TIndex* <span class="keyword">const</span> __restrict__ neighbors_index,</div>
<div class="line"><a name="l00138"></a><span class="lineno">  138</span>&#160;        <span class="keyword">const</span> TFeat* <span class="keyword">const</span> __restrict__ neighbors_importance,</div>
<div class="line"><a name="l00139"></a><span class="lineno">  139</span>&#160;        <span class="keyword">const</span> int64_t* <span class="keyword">const</span> __restrict__ neighbors_row_splits,</div>
<div class="line"><a name="l00140"></a><span class="lineno">  140</span>&#160;        <span class="keyword">const</span> TReal* <span class="keyword">const</span> __restrict__ extents,</div>
<div class="line"><a name="l00141"></a><span class="lineno">  141</span>&#160;        <span class="keyword">const</span> TReal* <span class="keyword">const</span> __restrict__ offsets,</div>
<div class="line"><a name="l00142"></a><span class="lineno">  142</span>&#160;        <span class="keyword">const</span> std::vector&lt;int&gt;&amp; filter_dims,</div>
<div class="line"><a name="l00143"></a><span class="lineno">  143</span>&#160;        <a class="code" href="namespaceopen3d_1_1ml_1_1impl.html#a1cdea72ec606986b7ada2e619ea41a8d">InterpolationMode</a> interpolation,</div>
<div class="line"><a name="l00144"></a><span class="lineno">  144</span>&#160;        <a class="code" href="namespaceopen3d_1_1ml_1_1impl.html#ad39d07a9288168e9ecab8f34e24d27fb">CoordinateMapping</a> coordinate_mapping,</div>
<div class="line"><a name="l00145"></a><span class="lineno">  145</span>&#160;        <span class="keywordtype">bool</span> align_corners,</div>
<div class="line"><a name="l00146"></a><span class="lineno">  146</span>&#160;        <span class="keywordtype">bool</span> individual_extent,</div>
<div class="line"><a name="l00147"></a><span class="lineno">  147</span>&#160;        <span class="keywordtype">bool</span> isotropic_extent,</div>
<div class="line"><a name="l00148"></a><span class="lineno">  148</span>&#160;        <span class="keywordtype">bool</span> normalize);</div>
<div class="line"><a name="l00149"></a><span class="lineno">  149</span>&#160; </div>
<div class="line"><a name="l00157"></a><span class="lineno">  157</span>&#160;<span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div>
<div class="line"><a name="l00158"></a><span class="lineno"><a class="line" href="namespaceopen3d_1_1ml_1_1impl.html#ab33c97667e644fa067e338616c765d98">  158</a></span>&#160;<span class="keywordtype">void</span> <a class="code" href="namespaceopen3d_1_1ml_1_1impl.html#ab33c97667e644fa067e338616c765d98">MultiplyColumns</a>(<span class="keyword">const</span> cudaStream_t&amp; stream,</div>
<div class="line"><a name="l00159"></a><span class="lineno">  159</span>&#160;                     <span class="keywordtype">size_t</span> rows,</div>
<div class="line"><a name="l00160"></a><span class="lineno">  160</span>&#160;                     <span class="keywordtype">size_t</span> cols,</div>
<div class="line"><a name="l00161"></a><span class="lineno">  161</span>&#160;                     T* __restrict__ col_major_matrix,</div>
<div class="line"><a name="l00162"></a><span class="lineno">  162</span>&#160;                     <span class="keyword">const</span> T* <span class="keyword">const</span> __restrict__ vector);</div>
<div class="line"><a name="l00163"></a><span class="lineno">  163</span>&#160; </div>
<div class="line"><a name="l00173"></a><span class="lineno">  173</span>&#160;<span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div>
<div class="line"><a name="l00174"></a><span class="lineno"><a class="line" href="namespaceopen3d_1_1ml_1_1impl.html#a5ada2e0303fe9ea6733181c936dd67a3">  174</a></span>&#160;<span class="keywordtype">void</span> <a class="code" href="namespaceopen3d_1_1ml_1_1impl.html#a5ada2e0303fe9ea6733181c936dd67a3">MultiplyAndCopyColumns</a>(<span class="keyword">const</span> cudaStream_t&amp; stream,</div>
<div class="line"><a name="l00175"></a><span class="lineno">  175</span>&#160;                            <span class="keywordtype">size_t</span> rows,</div>
<div class="line"><a name="l00176"></a><span class="lineno">  176</span>&#160;                            <span class="keywordtype">size_t</span> cols,</div>
<div class="line"><a name="l00177"></a><span class="lineno">  177</span>&#160;                            T* __restrict__ out_ptr,</div>
<div class="line"><a name="l00178"></a><span class="lineno">  178</span>&#160;                            <span class="keyword">const</span> T* <span class="keyword">const</span> __restrict__ col_major_matrix,</div>
<div class="line"><a name="l00179"></a><span class="lineno">  179</span>&#160;                            <span class="keyword">const</span> T* <span class="keyword">const</span> __restrict__ vector);</div>
<div class="line"><a name="l00180"></a><span class="lineno">  180</span>&#160; </div>
<div class="line"><a name="l00181"></a><span class="lineno">  181</span>&#160;}  <span class="comment">// namespace impl</span></div>
<div class="line"><a name="l00182"></a><span class="lineno">  182</span>&#160;}  <span class="comment">// namespace ml</span></div>
<div class="line"><a name="l00183"></a><span class="lineno">  183</span>&#160;}  <span class="comment">// namespace open3d</span></div>
<div class="ttc" id="a_coordinate_transformation_8cuh_html"><div class="ttname"><a href="_coordinate_transformation_8cuh.html">CoordinateTransformation.cuh</a></div></div>
<div class="ttc" id="anamespaceopen3d_1_1ml_1_1impl_html_a1cdea72ec606986b7ada2e619ea41a8d"><div class="ttname"><a href="namespaceopen3d_1_1ml_1_1impl.html#a1cdea72ec606986b7ada2e619ea41a8d">open3d::ml::impl::InterpolationMode</a></div><div class="ttdeci">InterpolationMode</div><div class="ttdef"><b>Definition:</b> ContinuousConvTypes.h:18</div></div>
<div class="ttc" id="anamespaceopen3d_1_1ml_1_1impl_html_a5ada2e0303fe9ea6733181c936dd67a3"><div class="ttname"><a href="namespaceopen3d_1_1ml_1_1impl.html#a5ada2e0303fe9ea6733181c936dd67a3">open3d::ml::impl::MultiplyAndCopyColumns</a></div><div class="ttdeci">void MultiplyAndCopyColumns(const cudaStream_t &amp;stream, size_t rows, size_t cols, T *__restrict__ out_ptr, const T *const __restrict__ col_major_matrix, const T *const __restrict__ vector)</div></div>
<div class="ttc" id="anamespaceopen3d_1_1ml_1_1impl_html_a915147ba8aa5ab252a532fa9823c9adb"><div class="ttname"><a href="namespaceopen3d_1_1ml_1_1impl.html#a915147ba8aa5ab252a532fa9823c9adb">open3d::ml::impl::FillColumnTranspose</a></div><div class="ttdeci">void FillColumnTranspose(const cudaStream_t &amp;stream, TFeat *columns, int in_channels, TIndex begin_idx, TIndex end_idx, TIndex num_out, const TReal *const __restrict__ out_positions, TIndex num_inp, const TReal *const __restrict__ inp_positions, const TFeat *const __restrict__ inp_features, const TFeat *const __restrict__ inp_neighbors_importance_sum, const int64_t *const __restrict__ inp_neighbors_prefix_sum, size_t neighbors_index_size, const TIndex *const __restrict__ neighbors_index, const TFeat *const __restrict__ neighbors_importance, const int64_t *const __restrict__ neighbors_row_splits, const TReal *const __restrict__ extents, const TReal *const __restrict__ offsets, const std::vector&lt; int &gt; &amp;filter_dims, InterpolationMode interpolation, CoordinateMapping coordinate_mapping, bool align_corners, bool individual_extent, bool isotropic_extent, bool normalize)</div></div>
<div class="ttc" id="anamespaceopen3d_1_1ml_1_1impl_html_ab33c97667e644fa067e338616c765d98"><div class="ttname"><a href="namespaceopen3d_1_1ml_1_1impl.html#ab33c97667e644fa067e338616c765d98">open3d::ml::impl::MultiplyColumns</a></div><div class="ttdeci">void MultiplyColumns(const cudaStream_t &amp;stream, size_t rows, size_t cols, T *__restrict__ col_major_matrix, const T *const __restrict__ vector)</div></div>
<div class="ttc" id="anamespaceopen3d_1_1ml_1_1impl_html_ad39d07a9288168e9ecab8f34e24d27fb"><div class="ttname"><a href="namespaceopen3d_1_1ml_1_1impl.html#ad39d07a9288168e9ecab8f34e24d27fb">open3d::ml::impl::CoordinateMapping</a></div><div class="ttdeci">CoordinateMapping</div><div class="ttdef"><b>Definition:</b> ContinuousConvTypes.h:26</div></div>
<div class="ttc" id="anamespaceopen3d_1_1ml_1_1impl_html_afac64bdddd123dfede9328296c820553"><div class="ttname"><a href="namespaceopen3d_1_1ml_1_1impl.html#afac64bdddd123dfede9328296c820553">open3d::ml::impl::FillColumn</a></div><div class="ttdeci">void FillColumn(const cudaStream_t &amp;stream, TFeat *columns, int in_channels, TIndex begin_idx, TIndex end_idx, TIndex num_out, const TReal *const __restrict__ out_positions, TIndex num_inp, const TReal *const __restrict__ inp_positions, const TFeat *const __restrict__ inp_features, const TFeat *const __restrict__ inp_importance, size_t neighbors_index_size, const TIndex *const __restrict__ neighbors_index, const TFeat *const __restrict__ neighbors_importance, const int64_t *const __restrict__ neighbors_row_splits, const TReal *const __restrict__ extents, const TReal *const __restrict__ offsets, const std::vector&lt; int &gt; &amp;filter_dims, InterpolationMode interpolation, CoordinateMapping coordinate_mapping, bool align_corners, bool individual_extent, bool isotropic_extent, bool normalize)</div></div>
<div class="ttc" id="anamespaceopen3d_html"><div class="ttname"><a href="namespaceopen3d.html">open3d</a></div><div class="ttdef"><b>Definition:</b> PinholeCameraIntrinsic.cpp:16</div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>

<!-- Mirrored from www.open3d.org/docs/release/cpp_api/_continuous_conv_c_u_d_a_kernels_8h_source.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 14 May 2023 11:04:55 GMT -->
</html>
