<!-- HTML header for doxygen 1.8.20-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<!-- Mirrored from www.open3d.org/docs/release/cpp_api/classopen3d_1_1geometry_1_1_tetra_mesh.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 14 May 2023 10:56:11 GMT -->
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Open3D (C++ API): open3d::geometry::TetraMesh Class Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    extensions: ["tex2jax.js", "TeX/AMSmath.html", "TeX/AMSsymbols.js"],
    jax: ["input/TeX","output/HTML-CSS"],
});
</script>
<script type="text/javascript" async="async" src="../../../../cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-3TQPKGV6Z3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-3TQPKGV6Z3');
</script>
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectlogo"><img alt="Logo" src="open3d_logo.ico"/></td>
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Open3D (C++ API)
   &#160;<span id="projectnumber">0.17.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.html');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.html','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespaceopen3d.html">open3d</a></li><li class="navelem"><a class="el" href="namespaceopen3d_1_1geometry.html">geometry</a></li><li class="navelem"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d">TetraMesh</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="#pub-static-methods">Static Public Member Functions</a> &#124;
<a href="#pub-attribs">Data Fields</a> &#124;
<a href="#pro-methods">Protected Member Functions</a>  </div>
  <div class="headertitle">
<div class="title">open3d::geometry::TetraMesh Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Tetra mesh contains vertices and tetrahedra represented by the indices to the vertices.  
 <a href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="_tetra_mesh_8h_source.html">TetraMesh.h</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for open3d::geometry::TetraMesh:</div>
<div class="dyncontent">
 <div class="center">
  <img src="classopen3d_1_1geometry_1_1_tetra_mesh.642.d" usemap="#open3d::geometry::TetraMesh_map" alt=""/>
  <map id="open3d::geometry::TetraMesh_map" name="open3d::geometry::TetraMesh_map">
<area href="classopen3d_1_1geometry_1_1_mesh_base.412.de" title="MeshBash Class." alt="open3d::geometry::MeshBase" shape="rect" coords="0,112,188,136"/>
<area href="classopen3d_1_1geometry_1_1_geometry3_d.402" title="The base geometry class for 3D geometries." alt="open3d::geometry::Geometry3D" shape="rect" coords="0,56,188,80"/>
<area href="classopen3d_1_1geometry_1_1_geometry.400.del" title="The base geometry class." alt="open3d::geometry::Geometry" shape="rect" coords="0,0,188,24"/>
  </map>
</div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a0fbac204193ea2d822c5ce0c19f011a4"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#a0fbac204193ea2d822c5ce0c19f011a4">TetraMesh</a> ()</td></tr>
<tr class="memdesc:a0fbac204193ea2d822c5ce0c19f011a4"><td class="mdescLeft">&#160;</td><td class="mdescRight">Default Constructor.  <a href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#a0fbac204193ea2d822c5ce0c19f011a4">More...</a><br /></td></tr>
<tr class="separator:a0fbac204193ea2d822c5ce0c19f011a4"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab80fb044ba732fc02a9a4435e645bf1a"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#ab80fb044ba732fc02a9a4435e645bf1a">TetraMesh</a> (const std::vector&lt; Eigen::Vector3d &gt; &amp;vertices, const std::vector&lt; Eigen::Vector4i, <a class="el" href="namespaceopen3d_1_1utility.html#a45f389dc4f9b98744280e86eeba44f55">utility::Vector4i_allocator</a> &gt; &amp;tetras)</td></tr>
<tr class="memdesc:ab80fb044ba732fc02a9a4435e645bf1a"><td class="mdescLeft">&#160;</td><td class="mdescRight">Parameterized Constructor.  <a href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#ab80fb044ba732fc02a9a4435e645bf1a">More...</a><br /></td></tr>
<tr class="separator:ab80fb044ba732fc02a9a4435e645bf1a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab88065080870cd79c7d9bfe8009f054b"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#ab88065080870cd79c7d9bfe8009f054b">~TetraMesh</a> () override</td></tr>
<tr class="separator:ab88065080870cd79c7d9bfe8009f054b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afe4d02411d4ea06cc631232d502042b0"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d">TetraMesh</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#afe4d02411d4ea06cc631232d502042b0">Clear</a> () override</td></tr>
<tr class="memdesc:afe4d02411d4ea06cc631232d502042b0"><td class="mdescLeft">&#160;</td><td class="mdescRight">Clear all elements in the geometry.  <a href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#afe4d02411d4ea06cc631232d502042b0">More...</a><br /></td></tr>
<tr class="separator:afe4d02411d4ea06cc631232d502042b0"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa19b3a91d236b24cdfd4433d64d4750d"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d">TetraMesh</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#aa19b3a91d236b24cdfd4433d64d4750d">operator+=</a> (const <a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d">TetraMesh</a> &amp;mesh)</td></tr>
<tr class="separator:aa19b3a91d236b24cdfd4433d64d4750d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9f104187a8638d87cfe983344fa5e19a"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d">TetraMesh</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#a9f104187a8638d87cfe983344fa5e19a">operator+</a> (const <a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d">TetraMesh</a> &amp;mesh) const</td></tr>
<tr class="separator:a9f104187a8638d87cfe983344fa5e19a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac65312e752910b46a48b3e2e3e950b12"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d">TetraMesh</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#ac65312e752910b46a48b3e2e3e950b12">RemoveDuplicatedVertices</a> ()</td></tr>
<tr class="memdesc:ac65312e752910b46a48b3e2e3e950b12"><td class="mdescLeft">&#160;</td><td class="mdescRight">Function that removes duplicated verties, i.e., vertices that have identical coordinates.  <a href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#ac65312e752910b46a48b3e2e3e950b12">More...</a><br /></td></tr>
<tr class="separator:ac65312e752910b46a48b3e2e3e950b12"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a235518d83020a961efe74bd56f638de6"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d">TetraMesh</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#a235518d83020a961efe74bd56f638de6">RemoveDuplicatedTetras</a> ()</td></tr>
<tr class="memdesc:a235518d83020a961efe74bd56f638de6"><td class="mdescLeft">&#160;</td><td class="mdescRight">Function that removes duplicated tetrahedra, i.e., removes tetrahedra that reference the same four vertices, independent of their order.  <a href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#a235518d83020a961efe74bd56f638de6">More...</a><br /></td></tr>
<tr class="separator:a235518d83020a961efe74bd56f638de6"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a11a1c3bcef014c4efcb68c89b054e419"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d">TetraMesh</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#a11a1c3bcef014c4efcb68c89b054e419">RemoveUnreferencedVertices</a> ()</td></tr>
<tr class="memdesc:a11a1c3bcef014c4efcb68c89b054e419"><td class="mdescLeft">&#160;</td><td class="mdescRight">This function removes vertices from the tetra mesh that are not referenced in any tetrahedron of the mesh.  <a href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#a11a1c3bcef014c4efcb68c89b054e419">More...</a><br /></td></tr>
<tr class="separator:a11a1c3bcef014c4efcb68c89b054e419"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a28eed6595966f37fe14a66eb1023e7c2"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d">TetraMesh</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#a28eed6595966f37fe14a66eb1023e7c2">RemoveDegenerateTetras</a> ()</td></tr>
<tr class="memdesc:a28eed6595966f37fe14a66eb1023e7c2"><td class="mdescLeft">&#160;</td><td class="mdescRight">Function that removes degenerate tetrahedra, i.e., tetrahedra that reference a single vertex multiple times in a single tetrahedron. They are usually the product of removing duplicated vertices.  <a href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#a28eed6595966f37fe14a66eb1023e7c2">More...</a><br /></td></tr>
<tr class="separator:a28eed6595966f37fe14a66eb1023e7c2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac6ec8f9e2e0c05a346502e277f31a91c"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#ac6ec8f9e2e0c05a346502e277f31a91c">HasTetras</a> () const</td></tr>
<tr class="memdesc:ac6ec8f9e2e0c05a346502e277f31a91c"><td class="mdescLeft">&#160;</td><td class="mdescRight">Returns <code>true</code> if the mesh contains tetras.  <a href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#ac6ec8f9e2e0c05a346502e277f31a91c">More...</a><br /></td></tr>
<tr class="separator:ac6ec8f9e2e0c05a346502e277f31a91c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a475f47cd1c304643f1b7ef4e6f846639"><td class="memItemLeft" align="right" valign="top">std::shared_ptr&lt; <a class="el" href="classopen3d_1_1geometry_1_1_triangle_mesh.40">TriangleMesh</a> &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#a475f47cd1c304643f1b7ef4e6f846639">ExtractTriangleMesh</a> (const std::vector&lt; double &gt; &amp;values, double level)</td></tr>
<tr class="memdesc:a475f47cd1c304643f1b7ef4e6f846639"><td class="mdescLeft">&#160;</td><td class="mdescRight">Function to extract a triangle mesh of the specified iso-surface at a level This method applies primal contouring and generates triangles for each tetrahedron.  <a href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#a475f47cd1c304643f1b7ef4e6f846639">More...</a><br /></td></tr>
<tr class="separator:a475f47cd1c304643f1b7ef4e6f846639"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_classopen3d_1_1geometry_1_1_mesh_base')"><img src="closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de">open3d::geometry::MeshBase</a></td></tr>
<tr class="memitem:a7f0a38e96630f55717dfd3392fe62aa4 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a7f0a38e96630f55717dfd3392fe62aa4">MeshBase</a> ()</td></tr>
<tr class="memdesc:a7f0a38e96630f55717dfd3392fe62aa4 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="mdescLeft">&#160;</td><td class="mdescRight">Default Constructor.  <a href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a7f0a38e96630f55717dfd3392fe62aa4">More...</a><br /></td></tr>
<tr class="separator:a7f0a38e96630f55717dfd3392fe62aa4 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a719475a1bc584de3df7deeda89217eb5 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a719475a1bc584de3df7deeda89217eb5">~MeshBase</a> () override</td></tr>
<tr class="separator:a719475a1bc584de3df7deeda89217eb5 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0968a4f71bdbbc116850df571f80272c inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top">virtual bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a0968a4f71bdbbc116850df571f80272c">IsEmpty</a> () const override</td></tr>
<tr class="memdesc:a0968a4f71bdbbc116850df571f80272c inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="mdescLeft">&#160;</td><td class="mdescRight">Returns <code>true</code> iff the geometry is empty.  <a href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a0968a4f71bdbbc116850df571f80272c">More...</a><br /></td></tr>
<tr class="separator:a0968a4f71bdbbc116850df571f80272c inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad6c4c2ef12c0a5a4d50d7974cb779d06 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top">virtual Eigen::Vector3d&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#ad6c4c2ef12c0a5a4d50d7974cb779d06">GetMinBound</a> () const override</td></tr>
<tr class="memdesc:ad6c4c2ef12c0a5a4d50d7974cb779d06 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="mdescLeft">&#160;</td><td class="mdescRight">Returns min bounds for geometry coordinates.  <a href="classopen3d_1_1geometry_1_1_mesh_base.412.de#ad6c4c2ef12c0a5a4d50d7974cb779d06">More...</a><br /></td></tr>
<tr class="separator:ad6c4c2ef12c0a5a4d50d7974cb779d06 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a36ceff192f28d34b1893bb592c535072 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top">virtual Eigen::Vector3d&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a36ceff192f28d34b1893bb592c535072">GetMaxBound</a> () const override</td></tr>
<tr class="memdesc:a36ceff192f28d34b1893bb592c535072 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="mdescLeft">&#160;</td><td class="mdescRight">Returns max bounds for geometry coordinates.  <a href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a36ceff192f28d34b1893bb592c535072">More...</a><br /></td></tr>
<tr class="separator:a36ceff192f28d34b1893bb592c535072 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aca7af34654077e96288094255aa10de5 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top">virtual Eigen::Vector3d&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#aca7af34654077e96288094255aa10de5">GetCenter</a> () const override</td></tr>
<tr class="memdesc:aca7af34654077e96288094255aa10de5 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="mdescLeft">&#160;</td><td class="mdescRight">Returns the center of the geometry coordinates.  <a href="classopen3d_1_1geometry_1_1_mesh_base.412.de#aca7af34654077e96288094255aa10de5">More...</a><br /></td></tr>
<tr class="separator:aca7af34654077e96288094255aa10de5 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a81a7bcbb473ab0d382f8a604fe01da47 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top">virtual <a class="el" href="classopen3d_1_1geometry_1_1_axis_aligned_bou">AxisAlignedBoundingBox</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a81a7bcbb473ab0d382f8a604fe01da47">GetAxisAlignedBoundingBox</a> () const override</td></tr>
<tr class="separator:a81a7bcbb473ab0d382f8a604fe01da47 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adf9583383d79c612d1396750f3ad190a inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top">virtual <a class="el" href="classopen3d_1_1geometry_1_1_oriented_boundin">OrientedBoundingBox</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#adf9583383d79c612d1396750f3ad190a">GetOrientedBoundingBox</a> (bool robust=false) const override</td></tr>
<tr class="separator:adf9583383d79c612d1396750f3ad190a inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3b821b781c20c9d1e2d3fd586763626e inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top">virtual <a class="el" href="classopen3d_1_1geometry_1_1_oriented_boundin">OrientedBoundingBox</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a3b821b781c20c9d1e2d3fd586763626e">GetMinimalOrientedBoundingBox</a> (bool robust=false) const override</td></tr>
<tr class="separator:a3b821b781c20c9d1e2d3fd586763626e inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a660867be2560d5690b6837dea7ccfac8 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top">virtual <a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de">MeshBase</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a660867be2560d5690b6837dea7ccfac8">Transform</a> (const Eigen::Matrix4d &amp;transformation) override</td></tr>
<tr class="memdesc:a660867be2560d5690b6837dea7ccfac8 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="mdescLeft">&#160;</td><td class="mdescRight">Apply transformation (4x4 matrix) to the geometry coordinates.  <a href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a660867be2560d5690b6837dea7ccfac8">More...</a><br /></td></tr>
<tr class="separator:a660867be2560d5690b6837dea7ccfac8 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa364e4164bb9dfd420732106a0046c3b inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top">virtual <a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de">MeshBase</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#aa364e4164bb9dfd420732106a0046c3b">Translate</a> (const Eigen::Vector3d &amp;translation, bool relative=true) override</td></tr>
<tr class="memdesc:aa364e4164bb9dfd420732106a0046c3b inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="mdescLeft">&#160;</td><td class="mdescRight">Apply translation to the geometry coordinates.  <a href="classopen3d_1_1geometry_1_1_mesh_base.412.de#aa364e4164bb9dfd420732106a0046c3b">More...</a><br /></td></tr>
<tr class="separator:aa364e4164bb9dfd420732106a0046c3b inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad300c61bbb35ea3b174b04f8eb5fa042 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top">virtual <a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de">MeshBase</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#ad300c61bbb35ea3b174b04f8eb5fa042">Scale</a> (const double scale, const Eigen::Vector3d &amp;center) override</td></tr>
<tr class="memdesc:ad300c61bbb35ea3b174b04f8eb5fa042 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="mdescLeft">&#160;</td><td class="mdescRight">Apply scaling to the geometry coordinates. Given a scaling factor \(s\), and center \(c\), a given point \(p\) is transformed according to \(s (p - c) + c\).  <a href="classopen3d_1_1geometry_1_1_mesh_base.412.de#ad300c61bbb35ea3b174b04f8eb5fa042">More...</a><br /></td></tr>
<tr class="separator:ad300c61bbb35ea3b174b04f8eb5fa042 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3fa1a882c26e318cc9d03b688e91a4f0 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top">virtual <a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de">MeshBase</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a3fa1a882c26e318cc9d03b688e91a4f0">Rotate</a> (const Eigen::Matrix3d &amp;R, const Eigen::Vector3d &amp;center) override</td></tr>
<tr class="memdesc:a3fa1a882c26e318cc9d03b688e91a4f0 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="mdescLeft">&#160;</td><td class="mdescRight">Apply rotation to the geometry coordinates and normals. Given a rotation matrix \(R\), and center \(c\), a given point \(p\) is transformed according to \(R (p - c) + c\).  <a href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a3fa1a882c26e318cc9d03b688e91a4f0">More...</a><br /></td></tr>
<tr class="separator:a3fa1a882c26e318cc9d03b688e91a4f0 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5f2e94203dc3b39392b9266407e00aac inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de">MeshBase</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a5f2e94203dc3b39392b9266407e00aac">operator+=</a> (const <a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de">MeshBase</a> &amp;mesh)</td></tr>
<tr class="separator:a5f2e94203dc3b39392b9266407e00aac inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ace2c246764d9cf09ccf582435570598a inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de">MeshBase</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#ace2c246764d9cf09ccf582435570598a">operator+</a> (const <a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de">MeshBase</a> &amp;mesh) const</td></tr>
<tr class="separator:ace2c246764d9cf09ccf582435570598a inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab7ee6962ded8a7de44d38f4e737fdad0 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#ab7ee6962ded8a7de44d38f4e737fdad0">HasVertices</a> () const</td></tr>
<tr class="memdesc:ab7ee6962ded8a7de44d38f4e737fdad0 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="mdescLeft">&#160;</td><td class="mdescRight">Returns <code>True</code> if the mesh contains vertices.  <a href="classopen3d_1_1geometry_1_1_mesh_base.412.de#ab7ee6962ded8a7de44d38f4e737fdad0">More...</a><br /></td></tr>
<tr class="separator:ab7ee6962ded8a7de44d38f4e737fdad0 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3e672e8e3eac58844656f81a1154b074 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a3e672e8e3eac58844656f81a1154b074">HasVertexNormals</a> () const</td></tr>
<tr class="memdesc:a3e672e8e3eac58844656f81a1154b074 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="mdescLeft">&#160;</td><td class="mdescRight">Returns <code>True</code> if the mesh contains vertex normals.  <a href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a3e672e8e3eac58844656f81a1154b074">More...</a><br /></td></tr>
<tr class="separator:a3e672e8e3eac58844656f81a1154b074 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a77341c2d09a3a5bbab23e92b3df88400 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a77341c2d09a3a5bbab23e92b3df88400">HasVertexColors</a> () const</td></tr>
<tr class="memdesc:a77341c2d09a3a5bbab23e92b3df88400 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="mdescLeft">&#160;</td><td class="mdescRight">Returns <code>True</code> if the mesh contains vertex colors.  <a href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a77341c2d09a3a5bbab23e92b3df88400">More...</a><br /></td></tr>
<tr class="separator:a77341c2d09a3a5bbab23e92b3df88400 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab0f5f6dc5af988b69c7d9f7ac4294bea inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de">MeshBase</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#ab0f5f6dc5af988b69c7d9f7ac4294bea">NormalizeNormals</a> ()</td></tr>
<tr class="memdesc:ab0f5f6dc5af988b69c7d9f7ac4294bea inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="mdescLeft">&#160;</td><td class="mdescRight">Normalize vertex normals to length 1.  <a href="classopen3d_1_1geometry_1_1_mesh_base.412.de#ab0f5f6dc5af988b69c7d9f7ac4294bea">More...</a><br /></td></tr>
<tr class="separator:ab0f5f6dc5af988b69c7d9f7ac4294bea inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a760c1f0ddd8fb5121309fbf5f439a881 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de">MeshBase</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a760c1f0ddd8fb5121309fbf5f439a881">PaintUniformColor</a> (const Eigen::Vector3d &amp;<a class="el" href="_triangle_mesh_buffers_8cpp.html#aa332976d803be75beb81e81af320bfcb">color</a>)</td></tr>
<tr class="memdesc:a760c1f0ddd8fb5121309fbf5f439a881 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="mdescLeft">&#160;</td><td class="mdescRight">Assigns each vertex in the <a class="el" href="classopen3d_1_1geometry_1_1_triangle_mesh.40" title="Triangle mesh contains vertices and triangles represented by the indices to the vertices.">TriangleMesh</a> the same color.  <a href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a760c1f0ddd8fb5121309fbf5f439a881">More...</a><br /></td></tr>
<tr class="separator:a760c1f0ddd8fb5121309fbf5f439a881 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8a818a84de36ef3b34f46ee1d5204684 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top">std::tuple&lt; std::shared_ptr&lt; <a class="el" href="classopen3d_1_1geometry_1_1_triangle_mesh.40">TriangleMesh</a> &gt;, std::vector&lt; size_t &gt; &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a8a818a84de36ef3b34f46ee1d5204684">ComputeConvexHull</a> () const</td></tr>
<tr class="memdesc:a8a818a84de36ef3b34f46ee1d5204684 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="mdescLeft">&#160;</td><td class="mdescRight">Function that computes the convex hull of the triangle mesh using qhull.  <a href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a8a818a84de36ef3b34f46ee1d5204684">More...</a><br /></td></tr>
<tr class="separator:a8a818a84de36ef3b34f46ee1d5204684 inherit pub_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_classopen3d_1_1geometry_1_1_geometry3_d')"><img src="closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402">open3d::geometry::Geometry3D</a></td></tr>
<tr class="memitem:a3bee61a0da428535d0eb9f62786fcab1 inherit pub_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402#a3bee61a0da428535d0eb9f62786fcab1">~Geometry3D</a> () override</td></tr>
<tr class="separator:a3bee61a0da428535d0eb9f62786fcab1 inherit pub_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5c2ab7fb19c0fc8f4ccbc9a776be2e23 inherit pub_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memItemLeft" align="right" valign="top">virtual <a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402">Geometry3D</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402#a5c2ab7fb19c0fc8f4ccbc9a776be2e23">Rotate</a> (const Eigen::Matrix3d &amp;R)</td></tr>
<tr class="separator:a5c2ab7fb19c0fc8f4ccbc9a776be2e23 inherit pub_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_classopen3d_1_1geometry_1_1_geometry"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_classopen3d_1_1geometry_1_1_geometry')"><img src="closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del">open3d::geometry::Geometry</a></td></tr>
<tr class="memitem:a1c2eb5a3e6c0a47cc31e38d086d07c54 inherit pub_methods_classopen3d_1_1geometry_1_1_geometry"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a1c2eb5a3e6c0a47cc31e38d086d07c54">~Geometry</a> ()</td></tr>
<tr class="separator:a1c2eb5a3e6c0a47cc31e38d086d07c54 inherit pub_methods_classopen3d_1_1geometry_1_1_geometry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a194473f920417162aa501bfb7df1d4b9 inherit pub_methods_classopen3d_1_1geometry_1_1_geometry"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a69975c2b054d4fd12cf36866a030ed8e">GeometryType</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a194473f920417162aa501bfb7df1d4b9">GetGeometryType</a> () const</td></tr>
<tr class="memdesc:a194473f920417162aa501bfb7df1d4b9 inherit pub_methods_classopen3d_1_1geometry_1_1_geometry"><td class="mdescLeft">&#160;</td><td class="mdescRight">Returns one of registered geometry types.  <a href="classopen3d_1_1geometry_1_1_geometry.400.del#a194473f920417162aa501bfb7df1d4b9">More...</a><br /></td></tr>
<tr class="separator:a194473f920417162aa501bfb7df1d4b9 inherit pub_methods_classopen3d_1_1geometry_1_1_geometry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a669ce49f3f489ec8816fb3ad228de081 inherit pub_methods_classopen3d_1_1geometry_1_1_geometry"><td class="memItemLeft" align="right" valign="top">int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a669ce49f3f489ec8816fb3ad228de081">Dimension</a> () const</td></tr>
<tr class="memdesc:a669ce49f3f489ec8816fb3ad228de081 inherit pub_methods_classopen3d_1_1geometry_1_1_geometry"><td class="mdescLeft">&#160;</td><td class="mdescRight">Returns whether the geometry is 2D or 3D.  <a href="classopen3d_1_1geometry_1_1_geometry.400.del#a669ce49f3f489ec8816fb3ad228de081">More...</a><br /></td></tr>
<tr class="separator:a669ce49f3f489ec8816fb3ad228de081 inherit pub_methods_classopen3d_1_1geometry_1_1_geometry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7cba98e39c57eb2544eedfb525807a06 inherit pub_methods_classopen3d_1_1geometry_1_1_geometry"><td class="memItemLeft" align="right" valign="top">std::string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a7cba98e39c57eb2544eedfb525807a06">GetName</a> () const</td></tr>
<tr class="separator:a7cba98e39c57eb2544eedfb525807a06 inherit pub_methods_classopen3d_1_1geometry_1_1_geometry"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4229d9bdaded622121f443cbb81626b8 inherit pub_methods_classopen3d_1_1geometry_1_1_geometry"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a4229d9bdaded622121f443cbb81626b8">SetName</a> (const std::string &amp;<a class="el" href="_o3_d_visualizer_8cpp.html#a9b45b3e13bd9167aab02e17e08916231">name</a>)</td></tr>
<tr class="separator:a4229d9bdaded622121f443cbb81626b8 inherit pub_methods_classopen3d_1_1geometry_1_1_geometry"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-static-methods"></a>
Static Public Member Functions</h2></td></tr>
<tr class="memitem:a1c90bf3a04d3474c65104bd4936b9145"><td class="memItemLeft" align="right" valign="top">static std::tuple&lt; std::shared_ptr&lt; <a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d">TetraMesh</a> &gt;, std::vector&lt; size_t &gt; &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#a1c90bf3a04d3474c65104bd4936b9145">CreateFromPointCloud</a> (const <a class="el" href="classopen3d_1_1geometry_1_1_point_cloud.41b">PointCloud</a> &amp;point_cloud)</td></tr>
<tr class="memdesc:a1c90bf3a04d3474c65104bd4936b9145"><td class="mdescLeft">&#160;</td><td class="mdescRight">Function that creates a tetrahedral mesh (<a class="el" href="_tetra_mesh_factory_8cpp.html">TetraMeshFactory.cpp</a>). from a point cloud.  <a href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#a1c90bf3a04d3474c65104bd4936b9145">More...</a><br /></td></tr>
<tr class="separator:a1c90bf3a04d3474c65104bd4936b9145"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td colspan="2" onclick="javascript:toggleInherit('pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d')"><img src="closed.png" alt="-"/>&#160;Static Public Member Functions inherited from <a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402">open3d::geometry::Geometry3D</a></td></tr>
<tr class="memitem:ab557dd1610ea7fae73d00c706bbd529f inherit pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memItemLeft" align="right" valign="top">static Eigen::Matrix3d&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402#ab557dd1610ea7fae73d00c706bbd529f">GetRotationMatrixFromXYZ</a> (const Eigen::Vector3d &amp;rotation)</td></tr>
<tr class="memdesc:ab557dd1610ea7fae73d00c706bbd529f inherit pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get Rotation Matrix from XYZ RotationType.  <a href="classopen3d_1_1geometry_1_1_geometry3_d.402#ab557dd1610ea7fae73d00c706bbd529f">More...</a><br /></td></tr>
<tr class="separator:ab557dd1610ea7fae73d00c706bbd529f inherit pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af5b8ef97b798c623b4e2fe72d2afda03 inherit pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memItemLeft" align="right" valign="top">static Eigen::Matrix3d&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402#af5b8ef97b798c623b4e2fe72d2afda03">GetRotationMatrixFromYZX</a> (const Eigen::Vector3d &amp;rotation)</td></tr>
<tr class="memdesc:af5b8ef97b798c623b4e2fe72d2afda03 inherit pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get Rotation Matrix from YZX RotationType.  <a href="classopen3d_1_1geometry_1_1_geometry3_d.402#af5b8ef97b798c623b4e2fe72d2afda03">More...</a><br /></td></tr>
<tr class="separator:af5b8ef97b798c623b4e2fe72d2afda03 inherit pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afbb9b2eabab1ced5c25358c3a69c8d13 inherit pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memItemLeft" align="right" valign="top">static Eigen::Matrix3d&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402#afbb9b2eabab1ced5c25358c3a69c8d13">GetRotationMatrixFromZXY</a> (const Eigen::Vector3d &amp;rotation)</td></tr>
<tr class="memdesc:afbb9b2eabab1ced5c25358c3a69c8d13 inherit pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get Rotation Matrix from ZXY RotationType.  <a href="classopen3d_1_1geometry_1_1_geometry3_d.402#afbb9b2eabab1ced5c25358c3a69c8d13">More...</a><br /></td></tr>
<tr class="separator:afbb9b2eabab1ced5c25358c3a69c8d13 inherit pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a82f91e4bddbb07a3ccd6692db599eca7 inherit pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memItemLeft" align="right" valign="top">static Eigen::Matrix3d&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402#a82f91e4bddbb07a3ccd6692db599eca7">GetRotationMatrixFromXZY</a> (const Eigen::Vector3d &amp;rotation)</td></tr>
<tr class="memdesc:a82f91e4bddbb07a3ccd6692db599eca7 inherit pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get Rotation Matrix from XZY RotationType.  <a href="classopen3d_1_1geometry_1_1_geometry3_d.402#a82f91e4bddbb07a3ccd6692db599eca7">More...</a><br /></td></tr>
<tr class="separator:a82f91e4bddbb07a3ccd6692db599eca7 inherit pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac96c4285c5d5cc80f14458559c7a3826 inherit pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memItemLeft" align="right" valign="top">static Eigen::Matrix3d&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402#ac96c4285c5d5cc80f14458559c7a3826">GetRotationMatrixFromZYX</a> (const Eigen::Vector3d &amp;rotation)</td></tr>
<tr class="memdesc:ac96c4285c5d5cc80f14458559c7a3826 inherit pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get Rotation Matrix from ZYX RotationType.  <a href="classopen3d_1_1geometry_1_1_geometry3_d.402#ac96c4285c5d5cc80f14458559c7a3826">More...</a><br /></td></tr>
<tr class="separator:ac96c4285c5d5cc80f14458559c7a3826 inherit pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a16ee2e4c68c2c55ac4ab8b533b11dad0 inherit pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memItemLeft" align="right" valign="top">static Eigen::Matrix3d&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402#a16ee2e4c68c2c55ac4ab8b533b11dad0">GetRotationMatrixFromYXZ</a> (const Eigen::Vector3d &amp;rotation)</td></tr>
<tr class="memdesc:a16ee2e4c68c2c55ac4ab8b533b11dad0 inherit pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get Rotation Matrix from YXZ RotationType.  <a href="classopen3d_1_1geometry_1_1_geometry3_d.402#a16ee2e4c68c2c55ac4ab8b533b11dad0">More...</a><br /></td></tr>
<tr class="separator:a16ee2e4c68c2c55ac4ab8b533b11dad0 inherit pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa9356dfe2ba6a44df60588f4b2a29056 inherit pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memItemLeft" align="right" valign="top">static Eigen::Matrix3d&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402#aa9356dfe2ba6a44df60588f4b2a29056">GetRotationMatrixFromAxisAngle</a> (const Eigen::Vector3d &amp;rotation)</td></tr>
<tr class="memdesc:aa9356dfe2ba6a44df60588f4b2a29056 inherit pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get Rotation Matrix from AxisAngle RotationType.  <a href="classopen3d_1_1geometry_1_1_geometry3_d.402#aa9356dfe2ba6a44df60588f4b2a29056">More...</a><br /></td></tr>
<tr class="separator:aa9356dfe2ba6a44df60588f4b2a29056 inherit pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad9966dec46a4808e5acd9318fa6bf73a inherit pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memItemLeft" align="right" valign="top">static Eigen::Matrix3d&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402#ad9966dec46a4808e5acd9318fa6bf73a">GetRotationMatrixFromQuaternion</a> (const Eigen::Vector4d &amp;rotation)</td></tr>
<tr class="memdesc:ad9966dec46a4808e5acd9318fa6bf73a inherit pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get Rotation Matrix from Quaternion.  <a href="classopen3d_1_1geometry_1_1_geometry3_d.402#ad9966dec46a4808e5acd9318fa6bf73a">More...</a><br /></td></tr>
<tr class="separator:ad9966dec46a4808e5acd9318fa6bf73a inherit pub_static_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-attribs"></a>
Data Fields</h2></td></tr>
<tr class="memitem:aea141d239284465e05446b3d11422d37"><td class="memItemLeft" align="right" valign="top">std::vector&lt; Eigen::Vector4i, <a class="el" href="namespaceopen3d_1_1utility.html#a45f389dc4f9b98744280e86eeba44f55">utility::Vector4i_allocator</a> &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#aea141d239284465e05446b3d11422d37">tetras_</a></td></tr>
<tr class="memdesc:aea141d239284465e05446b3d11422d37"><td class="mdescLeft">&#160;</td><td class="mdescRight">List of tetras denoted by the index of points forming the tetra.  <a href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#aea141d239284465e05446b3d11422d37">More...</a><br /></td></tr>
<tr class="separator:aea141d239284465e05446b3d11422d37"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_attribs_classopen3d_1_1geometry_1_1_mesh_base"><td colspan="2" onclick="javascript:toggleInherit('pub_attribs_classopen3d_1_1geometry_1_1_mesh_base')"><img src="closed.png" alt="-"/>&#160;Data Fields inherited from <a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de">open3d::geometry::MeshBase</a></td></tr>
<tr class="memitem:a004aeef2268433b07feb4ee32e560292 inherit pub_attribs_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top">std::vector&lt; Eigen::Vector3d &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a004aeef2268433b07feb4ee32e560292">vertices_</a></td></tr>
<tr class="memdesc:a004aeef2268433b07feb4ee32e560292 inherit pub_attribs_classopen3d_1_1geometry_1_1_mesh_base"><td class="mdescLeft">&#160;</td><td class="mdescRight">Vertex coordinates.  <a href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a004aeef2268433b07feb4ee32e560292">More...</a><br /></td></tr>
<tr class="separator:a004aeef2268433b07feb4ee32e560292 inherit pub_attribs_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad3d33d6cd75814858c797096c605fc55 inherit pub_attribs_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top">std::vector&lt; Eigen::Vector3d &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#ad3d33d6cd75814858c797096c605fc55">vertex_normals_</a></td></tr>
<tr class="memdesc:ad3d33d6cd75814858c797096c605fc55 inherit pub_attribs_classopen3d_1_1geometry_1_1_mesh_base"><td class="mdescLeft">&#160;</td><td class="mdescRight">Vertex normals.  <a href="classopen3d_1_1geometry_1_1_mesh_base.412.de#ad3d33d6cd75814858c797096c605fc55">More...</a><br /></td></tr>
<tr class="separator:ad3d33d6cd75814858c797096c605fc55 inherit pub_attribs_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a41ab85a9c0d063d22ddbe058daa86751 inherit pub_attribs_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top">std::vector&lt; Eigen::Vector3d &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a41ab85a9c0d063d22ddbe058daa86751">vertex_colors_</a></td></tr>
<tr class="memdesc:a41ab85a9c0d063d22ddbe058daa86751 inherit pub_attribs_classopen3d_1_1geometry_1_1_mesh_base"><td class="mdescLeft">&#160;</td><td class="mdescRight">RGB colors of vertices.  <a href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a41ab85a9c0d063d22ddbe058daa86751">More...</a><br /></td></tr>
<tr class="separator:a41ab85a9c0d063d22ddbe058daa86751 inherit pub_attribs_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pro-methods"></a>
Protected Member Functions</h2></td></tr>
<tr class="memitem:a32d18d667d1f00a2d0e6836c06e92907"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d#a32d18d667d1f00a2d0e6836c06e92907">TetraMesh</a> (<a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a69975c2b054d4fd12cf36866a030ed8e">Geometry::GeometryType</a> <a class="el" href="io_2file__format_2_file_p_c_d_8cpp.375.delay#aff17911edc8208aa8ddb1c7c52c78389">type</a>)</td></tr>
<tr class="separator:a32d18d667d1f00a2d0e6836c06e92907"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pro_methods_classopen3d_1_1geometry_1_1_mesh_base"><td colspan="2" onclick="javascript:toggleInherit('pro_methods_classopen3d_1_1geometry_1_1_mesh_base')"><img src="closed.png" alt="-"/>&#160;Protected Member Functions inherited from <a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de">open3d::geometry::MeshBase</a></td></tr>
<tr class="memitem:a07940523af0c82dff28ca957845b1088 inherit pro_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a07940523af0c82dff28ca957845b1088">MeshBase</a> (<a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a69975c2b054d4fd12cf36866a030ed8e">Geometry::GeometryType</a> <a class="el" href="io_2file__format_2_file_p_c_d_8cpp.375.delay#aff17911edc8208aa8ddb1c7c52c78389">type</a>)</td></tr>
<tr class="separator:a07940523af0c82dff28ca957845b1088 inherit pro_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5267f51298df2bf8a85eba695396c7ad inherit pro_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a5267f51298df2bf8a85eba695396c7ad">MeshBase</a> (<a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a69975c2b054d4fd12cf36866a030ed8e">Geometry::GeometryType</a> <a class="el" href="io_2file__format_2_file_p_c_d_8cpp.375.delay#aff17911edc8208aa8ddb1c7c52c78389">type</a>, const std::vector&lt; Eigen::Vector3d &gt; &amp;vertices)</td></tr>
<tr class="separator:a5267f51298df2bf8a85eba695396c7ad inherit pro_methods_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td colspan="2" onclick="javascript:toggleInherit('pro_methods_classopen3d_1_1geometry_1_1_geometry3_d')"><img src="closed.png" alt="-"/>&#160;Protected Member Functions inherited from <a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402">open3d::geometry::Geometry3D</a></td></tr>
<tr class="memitem:ab7c4a13882fb57765e55e164e34eedfb inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402#ab7c4a13882fb57765e55e164e34eedfb">Geometry3D</a> (<a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a69975c2b054d4fd12cf36866a030ed8e">GeometryType</a> <a class="el" href="io_2file__format_2_file_p_c_d_8cpp.375.delay#aff17911edc8208aa8ddb1c7c52c78389">type</a>)</td></tr>
<tr class="memdesc:ab7c4a13882fb57765e55e164e34eedfb inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Parameterized Constructor.  <a href="classopen3d_1_1geometry_1_1_geometry3_d.402#ab7c4a13882fb57765e55e164e34eedfb">More...</a><br /></td></tr>
<tr class="separator:ab7c4a13882fb57765e55e164e34eedfb inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa03dcc177e8b50632e95d7dd7d838976 inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memItemLeft" align="right" valign="top">Eigen::Vector3d&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402#aa03dcc177e8b50632e95d7dd7d838976">ComputeMinBound</a> (const std::vector&lt; Eigen::Vector3d &gt; &amp;<a class="el" href="io_2file__format_2_file_p_c_d_8cpp.375.delay#af7f8f4a4e39e09fdb5e9f02330ecabef">points</a>) const</td></tr>
<tr class="memdesc:aa03dcc177e8b50632e95d7dd7d838976 inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Compute min bound of a list points.  <a href="classopen3d_1_1geometry_1_1_geometry3_d.402#aa03dcc177e8b50632e95d7dd7d838976">More...</a><br /></td></tr>
<tr class="separator:aa03dcc177e8b50632e95d7dd7d838976 inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a487b1d81a14ef17bf70e8c4d94d5c18c inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memItemLeft" align="right" valign="top">Eigen::Vector3d&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402#a487b1d81a14ef17bf70e8c4d94d5c18c">ComputeMaxBound</a> (const std::vector&lt; Eigen::Vector3d &gt; &amp;<a class="el" href="io_2file__format_2_file_p_c_d_8cpp.375.delay#af7f8f4a4e39e09fdb5e9f02330ecabef">points</a>) const</td></tr>
<tr class="memdesc:a487b1d81a14ef17bf70e8c4d94d5c18c inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Compute max bound of a list points.  <a href="classopen3d_1_1geometry_1_1_geometry3_d.402#a487b1d81a14ef17bf70e8c4d94d5c18c">More...</a><br /></td></tr>
<tr class="separator:a487b1d81a14ef17bf70e8c4d94d5c18c inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac8e6a432ab26afcb7fb572313ddc90ce inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memItemLeft" align="right" valign="top">Eigen::Vector3d&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402#ac8e6a432ab26afcb7fb572313ddc90ce">ComputeCenter</a> (const std::vector&lt; Eigen::Vector3d &gt; &amp;<a class="el" href="io_2file__format_2_file_p_c_d_8cpp.375.delay#af7f8f4a4e39e09fdb5e9f02330ecabef">points</a>) const</td></tr>
<tr class="memdesc:ac8e6a432ab26afcb7fb572313ddc90ce inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Computer center of a list of points.  <a href="classopen3d_1_1geometry_1_1_geometry3_d.402#ac8e6a432ab26afcb7fb572313ddc90ce">More...</a><br /></td></tr>
<tr class="separator:ac8e6a432ab26afcb7fb572313ddc90ce inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1fb3da9e31897b4279f02327daca34cd inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402#a1fb3da9e31897b4279f02327daca34cd">ResizeAndPaintUniformColor</a> (std::vector&lt; Eigen::Vector3d &gt; &amp;colors, const size_t <a class="el" href="io_2file__format_2_file_p_c_d_8cpp.375.delay#a439227feff9d7f55384e8780cfc2eb82">size</a>, const Eigen::Vector3d &amp;<a class="el" href="_triangle_mesh_buffers_8cpp.html#aa332976d803be75beb81e81af320bfcb">color</a>) const</td></tr>
<tr class="memdesc:a1fb3da9e31897b4279f02327daca34cd inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Resizes the colors vector and paints a uniform color.  <a href="classopen3d_1_1geometry_1_1_geometry3_d.402#a1fb3da9e31897b4279f02327daca34cd">More...</a><br /></td></tr>
<tr class="separator:a1fb3da9e31897b4279f02327daca34cd inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0e3a5c603c2c9a0e05c1af1a4a279508 inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402#a0e3a5c603c2c9a0e05c1af1a4a279508">TransformPoints</a> (const Eigen::Matrix4d &amp;transformation, std::vector&lt; Eigen::Vector3d &gt; &amp;<a class="el" href="io_2file__format_2_file_p_c_d_8cpp.375.delay#af7f8f4a4e39e09fdb5e9f02330ecabef">points</a>) const</td></tr>
<tr class="memdesc:a0e3a5c603c2c9a0e05c1af1a4a279508 inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Transforms all points with the transformation matrix.  <a href="classopen3d_1_1geometry_1_1_geometry3_d.402#a0e3a5c603c2c9a0e05c1af1a4a279508">More...</a><br /></td></tr>
<tr class="separator:a0e3a5c603c2c9a0e05c1af1a4a279508 inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac1df456f2e6dddac794f7ab2186a7ce5 inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402#ac1df456f2e6dddac794f7ab2186a7ce5">TransformNormals</a> (const Eigen::Matrix4d &amp;transformation, std::vector&lt; Eigen::Vector3d &gt; &amp;normals) const</td></tr>
<tr class="memdesc:ac1df456f2e6dddac794f7ab2186a7ce5 inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Transforms the normals with the transformation matrix.  <a href="classopen3d_1_1geometry_1_1_geometry3_d.402#ac1df456f2e6dddac794f7ab2186a7ce5">More...</a><br /></td></tr>
<tr class="separator:ac1df456f2e6dddac794f7ab2186a7ce5 inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a623c3e7c883e0bcfc2987aaf92c96597 inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402#a623c3e7c883e0bcfc2987aaf92c96597">TransformCovariances</a> (const Eigen::Matrix4d &amp;transformation, std::vector&lt; Eigen::Matrix3d &gt; &amp;covariances) const</td></tr>
<tr class="memdesc:a623c3e7c883e0bcfc2987aaf92c96597 inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Transforms all covariance matrices with the transformation.  <a href="classopen3d_1_1geometry_1_1_geometry3_d.402#a623c3e7c883e0bcfc2987aaf92c96597">More...</a><br /></td></tr>
<tr class="separator:a623c3e7c883e0bcfc2987aaf92c96597 inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a4029dff278938fcf7eb73b4133f76e67 inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402#a4029dff278938fcf7eb73b4133f76e67">TranslatePoints</a> (const Eigen::Vector3d &amp;translation, std::vector&lt; Eigen::Vector3d &gt; &amp;<a class="el" href="io_2file__format_2_file_p_c_d_8cpp.375.delay#af7f8f4a4e39e09fdb5e9f02330ecabef">points</a>, bool relative) const</td></tr>
<tr class="memdesc:a4029dff278938fcf7eb73b4133f76e67 inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Apply translation to the geometry coordinates.  <a href="classopen3d_1_1geometry_1_1_geometry3_d.402#a4029dff278938fcf7eb73b4133f76e67">More...</a><br /></td></tr>
<tr class="separator:a4029dff278938fcf7eb73b4133f76e67 inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a26106b31a3acecad90f44293c83a3a1b inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402#a26106b31a3acecad90f44293c83a3a1b">ScalePoints</a> (const double scale, std::vector&lt; Eigen::Vector3d &gt; &amp;<a class="el" href="io_2file__format_2_file_p_c_d_8cpp.375.delay#af7f8f4a4e39e09fdb5e9f02330ecabef">points</a>, const Eigen::Vector3d &amp;center) const</td></tr>
<tr class="memdesc:a26106b31a3acecad90f44293c83a3a1b inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Scale the coordinates of all points by the scaling factor <code>scale</code>.  <a href="classopen3d_1_1geometry_1_1_geometry3_d.402#a26106b31a3acecad90f44293c83a3a1b">More...</a><br /></td></tr>
<tr class="separator:a26106b31a3acecad90f44293c83a3a1b inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a901a9fda0a2b40a8a53ea45ff18a1760 inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402#a901a9fda0a2b40a8a53ea45ff18a1760">RotatePoints</a> (const Eigen::Matrix3d &amp;R, std::vector&lt; Eigen::Vector3d &gt; &amp;<a class="el" href="io_2file__format_2_file_p_c_d_8cpp.375.delay#af7f8f4a4e39e09fdb5e9f02330ecabef">points</a>, const Eigen::Vector3d &amp;center) const</td></tr>
<tr class="memdesc:a901a9fda0a2b40a8a53ea45ff18a1760 inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Rotate all points with the rotation matrix <code>R</code>.  <a href="classopen3d_1_1geometry_1_1_geometry3_d.402#a901a9fda0a2b40a8a53ea45ff18a1760">More...</a><br /></td></tr>
<tr class="separator:a901a9fda0a2b40a8a53ea45ff18a1760 inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa2448e4cfbdb49e90e72289e36113d9b inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402#aa2448e4cfbdb49e90e72289e36113d9b">RotateNormals</a> (const Eigen::Matrix3d &amp;R, std::vector&lt; Eigen::Vector3d &gt; &amp;normals) const</td></tr>
<tr class="memdesc:aa2448e4cfbdb49e90e72289e36113d9b inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Rotate all normals with the rotation matrix <code>R</code>.  <a href="classopen3d_1_1geometry_1_1_geometry3_d.402#aa2448e4cfbdb49e90e72289e36113d9b">More...</a><br /></td></tr>
<tr class="separator:aa2448e4cfbdb49e90e72289e36113d9b inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9ce8a11fd0762558a620f448f18ebae3 inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry3_d.402#a9ce8a11fd0762558a620f448f18ebae3">RotateCovariances</a> (const Eigen::Matrix3d &amp;R, std::vector&lt; Eigen::Matrix3d &gt; &amp;covariances) const</td></tr>
<tr class="memdesc:a9ce8a11fd0762558a620f448f18ebae3 inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Rotate all covariance matrices with the rotation matrix <code>R</code>.  <a href="classopen3d_1_1geometry_1_1_geometry3_d.402#a9ce8a11fd0762558a620f448f18ebae3">More...</a><br /></td></tr>
<tr class="separator:a9ce8a11fd0762558a620f448f18ebae3 inherit pro_methods_classopen3d_1_1geometry_1_1_geometry3_d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pro_methods_classopen3d_1_1geometry_1_1_geometry"><td colspan="2" onclick="javascript:toggleInherit('pro_methods_classopen3d_1_1geometry_1_1_geometry')"><img src="closed.png" alt="-"/>&#160;Protected Member Functions inherited from <a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del">open3d::geometry::Geometry</a></td></tr>
<tr class="memitem:ae0bb1c2bed5d65d1ecd0e81370a12d99 inherit pro_methods_classopen3d_1_1geometry_1_1_geometry"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#ae0bb1c2bed5d65d1ecd0e81370a12d99">Geometry</a> (<a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a69975c2b054d4fd12cf36866a030ed8e">GeometryType</a> <a class="el" href="io_2file__format_2_file_p_c_d_8cpp.375.delay#aff17911edc8208aa8ddb1c7c52c78389">type</a>, int dimension)</td></tr>
<tr class="memdesc:ae0bb1c2bed5d65d1ecd0e81370a12d99 inherit pro_methods_classopen3d_1_1geometry_1_1_geometry"><td class="mdescLeft">&#160;</td><td class="mdescRight">Parameterized Constructor.  <a href="classopen3d_1_1geometry_1_1_geometry.400.del#ae0bb1c2bed5d65d1ecd0e81370a12d99">More...</a><br /></td></tr>
<tr class="separator:ae0bb1c2bed5d65d1ecd0e81370a12d99 inherit pro_methods_classopen3d_1_1geometry_1_1_geometry"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="inherited"></a>
Additional Inherited Members</h2></td></tr>
<tr class="inherit_header pub_types_classopen3d_1_1geometry_1_1_mesh_base"><td colspan="2" onclick="javascript:toggleInherit('pub_types_classopen3d_1_1geometry_1_1_mesh_base')"><img src="closed.png" alt="-"/>&#160;Public Types inherited from <a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de">open3d::geometry::MeshBase</a></td></tr>
<tr class="memitem:a84f9db88a4d0d23d755136ddfa7e6bd7 inherit pub_types_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top">enum class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a84f9db88a4d0d23d755136ddfa7e6bd7">SimplificationContraction</a> { <a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a84f9db88a4d0d23d755136ddfa7e6bd7ab1897515d548a960afe49ecf66a29021">Average</a>
, <a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a84f9db88a4d0d23d755136ddfa7e6bd7add6dfa467092f93b67f60fb75476b794">Quadric</a>
 }</td></tr>
<tr class="memdesc:a84f9db88a4d0d23d755136ddfa7e6bd7"><td class="mdescLeft">&#160;</td><td class="mdescRight">Indicates the method that is used for mesh simplification if multiple vertices are combined to a single one.  <a href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a84f9db88a4d0d23d755136ddfa7e6bd7">More...</a><br /></td></tr>
<tr class="separator:a84f9db88a4d0d23d755136ddfa7e6bd7 inherit pub_types_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af63b2a09012544530c370e7a3828c89c inherit pub_types_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top">enum class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#af63b2a09012544530c370e7a3828c89c">FilterScope</a> { <a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#af63b2a09012544530c370e7a3828c89cab1c94ca2fbc3e78fc30069c8d0f01680">All</a>
, <a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#af63b2a09012544530c370e7a3828c89cacb5feb1b7314637725a2e73bdc9f7295">Color</a>
, <a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#af63b2a09012544530c370e7a3828c89ca960b44c579bc2f6818d2daaf9e4c16f0">Normal</a>
, <a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#af63b2a09012544530c370e7a3828c89cab22b929ba52471a02d18bb3a4e4472e6">Vertex</a>
 }</td></tr>
<tr class="memdesc:af63b2a09012544530c370e7a3828c89c"><td class="mdescLeft">&#160;</td><td class="mdescRight">Indicates the scope of filter operations.  <a href="classopen3d_1_1geometry_1_1_mesh_base.412.de#af63b2a09012544530c370e7a3828c89c">More...</a><br /></td></tr>
<tr class="separator:af63b2a09012544530c370e7a3828c89c inherit pub_types_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6f7e206d12e10f059ca530cd04c4d07a inherit pub_types_classopen3d_1_1geometry_1_1_mesh_base"><td class="memItemLeft" align="right" valign="top">enum class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a6f7e206d12e10f059ca530cd04c4d07a">DeformAsRigidAsPossibleEnergy</a> { <a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a6f7e206d12e10f059ca530cd04c4d07aa111552792d2df37209e4e9815a8524a8">Spokes</a>
, <a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#a6f7e206d12e10f059ca530cd04c4d07aac5d48c613aa395e2f92d06e97b85aa97">Smoothed</a>
 }</td></tr>
<tr class="separator:a6f7e206d12e10f059ca530cd04c4d07a inherit pub_types_classopen3d_1_1geometry_1_1_mesh_base"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_types_classopen3d_1_1geometry_1_1_geometry"><td colspan="2" onclick="javascript:toggleInherit('pub_types_classopen3d_1_1geometry_1_1_geometry')"><img src="closed.png" alt="-"/>&#160;Public Types inherited from <a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del">open3d::geometry::Geometry</a></td></tr>
<tr class="memitem:a69975c2b054d4fd12cf36866a030ed8e inherit pub_types_classopen3d_1_1geometry_1_1_geometry"><td class="memItemLeft" align="right" valign="top">enum class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a69975c2b054d4fd12cf36866a030ed8e">GeometryType</a> { <br />
&#160;&#160;<a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a69975c2b054d4fd12cf36866a030ed8ea6fcdc090caeade09d0efd6253932b6f5">Unspecified</a> = 0
, <a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a69975c2b054d4fd12cf36866a030ed8eaee9349b5cdfd717c7e1234edce6b72fa">PointCloud</a> = 1
, <a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a69975c2b054d4fd12cf36866a030ed8ea7fe2447f30c8de08b433c3631d7d78ff">VoxelGrid</a> = 2
, <a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a69975c2b054d4fd12cf36866a030ed8ea3d33fe96c4d284d37a6ee296db5e33ac">Octree</a> = 3
, <br />
&#160;&#160;<a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a69975c2b054d4fd12cf36866a030ed8eae3e5995e4fc46bdc12e733558dd3120a">LineSet</a> = 4
, <a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a69975c2b054d4fd12cf36866a030ed8ea2ad6a25f1ccff1433467bae74193446e">MeshBase</a> = 5
, <a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a69975c2b054d4fd12cf36866a030ed8ea70be243de75004a602f012fece7c0fad">TriangleMesh</a> = 6
, <a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a69975c2b054d4fd12cf36866a030ed8eaa79a2e14e35ed8368058ad93d3d39dc3">HalfEdgeTriangleMesh</a> = 7
, <br />
&#160;&#160;<a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a69975c2b054d4fd12cf36866a030ed8eabe53a0541a6d36f6ecb879fa2c584b08">Image</a> = 8
, <a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a69975c2b054d4fd12cf36866a030ed8ea7d64b6deb2cbf0f1712bd6e93b5755ba">RGBDImage</a> = 9
, <a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a69975c2b054d4fd12cf36866a030ed8ea48e9695b4242a3a90ea76c7cc87162de">TetraMesh</a> = 10
, <a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a69975c2b054d4fd12cf36866a030ed8eaff8b20067506aaf814f1e5df2494c2f1">OrientedBoundingBox</a> = 11
, <br />
&#160;&#160;<a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a69975c2b054d4fd12cf36866a030ed8ea0446516d578c6abaae2f3adc7239fa61">AxisAlignedBoundingBox</a> = 12
<br />
 }</td></tr>
<tr class="memdesc:a69975c2b054d4fd12cf36866a030ed8e"><td class="mdescLeft">&#160;</td><td class="mdescRight">Specifies possible geometry types.  <a href="classopen3d_1_1geometry_1_1_geometry.400.del#a69975c2b054d4fd12cf36866a030ed8e">More...</a><br /></td></tr>
<tr class="separator:a69975c2b054d4fd12cf36866a030ed8e inherit pub_types_classopen3d_1_1geometry_1_1_geometry"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Tetra mesh contains vertices and tetrahedra represented by the indices to the vertices. </p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a id="a0fbac204193ea2d822c5ce0c19f011a4"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a0fbac204193ea2d822c5ce0c19f011a4">&#9670;&nbsp;</a></span>TetraMesh() <span class="overload">[1/3]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">open3d::geometry::TetraMesh::TetraMesh </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Default Constructor. </p>

</div>
</div>
<a id="ab80fb044ba732fc02a9a4435e645bf1a"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ab80fb044ba732fc02a9a4435e645bf1a">&#9670;&nbsp;</a></span>TetraMesh() <span class="overload">[2/3]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">open3d::geometry::TetraMesh::TetraMesh </td>
          <td>(</td>
          <td class="paramtype">const std::vector&lt; Eigen::Vector3d &gt; &amp;&#160;</td>
          <td class="paramname"><em>vertices</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const std::vector&lt; Eigen::Vector4i, <a class="el" href="namespaceopen3d_1_1utility.html#a45f389dc4f9b98744280e86eeba44f55">utility::Vector4i_allocator</a> &gt; &amp;&#160;</td>
          <td class="paramname"><em>tetras</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Parameterized Constructor. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">vertices</td><td>Vertex coordinates. </td></tr>
    <tr><td class="paramname">tetras</td><td>List of tetras denoted by the index of points forming the tetra. </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="ab88065080870cd79c7d9bfe8009f054b"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ab88065080870cd79c7d9bfe8009f054b">&#9670;&nbsp;</a></span>~TetraMesh()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">open3d::geometry::TetraMesh::~TetraMesh </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">override</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a32d18d667d1f00a2d0e6836c06e92907"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a32d18d667d1f00a2d0e6836c06e92907">&#9670;&nbsp;</a></span>TetraMesh() <span class="overload">[3/3]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">open3d::geometry::TetraMesh::TetraMesh </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="classopen3d_1_1geometry_1_1_geometry.400.del#a69975c2b054d4fd12cf36866a030ed8e">Geometry::GeometryType</a>&#160;</td>
          <td class="paramname"><em>type</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a id="afe4d02411d4ea06cc631232d502042b0"></a>
<h2 class="memtitle"><span class="permalink"><a href="#afe4d02411d4ea06cc631232d502042b0">&#9670;&nbsp;</a></span>Clear()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d">TetraMesh</a> &amp; open3d::geometry::TetraMesh::Clear </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">override</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Clear all elements in the geometry. </p>

<p>Reimplemented from <a class="el" href="classopen3d_1_1geometry_1_1_mesh_base.412.de#ac3f81cdfc14b1fe903f2d5c3bd3b9cd7">open3d::geometry::MeshBase</a>.</p>

</div>
</div>
<a id="a1c90bf3a04d3474c65104bd4936b9145"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a1c90bf3a04d3474c65104bd4936b9145">&#9670;&nbsp;</a></span>CreateFromPointCloud()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">std::tuple&lt; std::shared_ptr&lt; <a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d">TetraMesh</a> &gt;, std::vector&lt; size_t &gt; &gt; open3d::geometry::TetraMesh::CreateFromPointCloud </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="classopen3d_1_1geometry_1_1_point_cloud.41b">PointCloud</a> &amp;&#160;</td>
          <td class="paramname"><em>point_cloud</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Function that creates a tetrahedral mesh (<a class="el" href="_tetra_mesh_factory_8cpp.html">TetraMeshFactory.cpp</a>). from a point cloud. </p>
<p>The method creates the Delaunay triangulation using the implementation from <a class="el" href="classopen3d_1_1geometry_1_1_qhull.41e.delaye">Qhull</a>. </p>

</div>
</div>
<a id="a475f47cd1c304643f1b7ef4e6f846639"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a475f47cd1c304643f1b7ef4e6f846639">&#9670;&nbsp;</a></span>ExtractTriangleMesh()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::shared_ptr&lt; <a class="el" href="classopen3d_1_1geometry_1_1_triangle_mesh.40">TriangleMesh</a> &gt; open3d::geometry::TetraMesh::ExtractTriangleMesh </td>
          <td>(</td>
          <td class="paramtype">const std::vector&lt; double &gt; &amp;&#160;</td>
          <td class="paramname"><em>values</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">double&#160;</td>
          <td class="paramname"><em>level</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Function to extract a triangle mesh of the specified iso-surface at a level This method applies primal contouring and generates triangles for each tetrahedron. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">level</td><td>specifies the level. </td></tr>
    <tr><td class="paramname">values</td><td>specifies values per-vertex. </td></tr>
  </table>
  </dd>
</dl>

</div>
</div>
<a id="ac6ec8f9e2e0c05a346502e277f31a91c"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ac6ec8f9e2e0c05a346502e277f31a91c">&#9670;&nbsp;</a></span>HasTetras()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">bool open3d::geometry::TetraMesh::HasTetras </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Returns <code>true</code> if the mesh contains tetras. </p>

</div>
</div>
<a id="a9f104187a8638d87cfe983344fa5e19a"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a9f104187a8638d87cfe983344fa5e19a">&#9670;&nbsp;</a></span>operator+()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d">TetraMesh</a> open3d::geometry::TetraMesh::operator+ </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d">TetraMesh</a> &amp;&#160;</td>
          <td class="paramname"><em>mesh</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="aa19b3a91d236b24cdfd4433d64d4750d"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aa19b3a91d236b24cdfd4433d64d4750d">&#9670;&nbsp;</a></span>operator+=()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d">TetraMesh</a> &amp; open3d::geometry::TetraMesh::operator+= </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d">TetraMesh</a> &amp;&#160;</td>
          <td class="paramname"><em>mesh</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a28eed6595966f37fe14a66eb1023e7c2"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a28eed6595966f37fe14a66eb1023e7c2">&#9670;&nbsp;</a></span>RemoveDegenerateTetras()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d">TetraMesh</a> &amp; open3d::geometry::TetraMesh::RemoveDegenerateTetras </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Function that removes degenerate tetrahedra, i.e., tetrahedra that reference a single vertex multiple times in a single tetrahedron. They are usually the product of removing duplicated vertices. </p>

</div>
</div>
<a id="a235518d83020a961efe74bd56f638de6"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a235518d83020a961efe74bd56f638de6">&#9670;&nbsp;</a></span>RemoveDuplicatedTetras()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d">TetraMesh</a> &amp; open3d::geometry::TetraMesh::RemoveDuplicatedTetras </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Function that removes duplicated tetrahedra, i.e., removes tetrahedra that reference the same four vertices, independent of their order. </p>

</div>
</div>
<a id="ac65312e752910b46a48b3e2e3e950b12"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ac65312e752910b46a48b3e2e3e950b12">&#9670;&nbsp;</a></span>RemoveDuplicatedVertices()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d">TetraMesh</a> &amp; open3d::geometry::TetraMesh::RemoveDuplicatedVertices </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Function that removes duplicated verties, i.e., vertices that have identical coordinates. </p>

</div>
</div>
<a id="a11a1c3bcef014c4efcb68c89b054e419"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a11a1c3bcef014c4efcb68c89b054e419">&#9670;&nbsp;</a></span>RemoveUnreferencedVertices()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classopen3d_1_1geometry_1_1_tetra_mesh.423.d">TetraMesh</a> &amp; open3d::geometry::TetraMesh::RemoveUnreferencedVertices </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>This function removes vertices from the tetra mesh that are not referenced in any tetrahedron of the mesh. </p>

</div>
</div>
<h2 class="groupheader">Field Documentation</h2>
<a id="aea141d239284465e05446b3d11422d37"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aea141d239284465e05446b3d11422d37">&#9670;&nbsp;</a></span>tetras_</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::vector&lt;Eigen::Vector4i, <a class="el" href="namespaceopen3d_1_1utility.html#a45f389dc4f9b98744280e86eeba44f55">utility::Vector4i_allocator</a>&gt; open3d::geometry::TetraMesh::tetras_</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>List of tetras denoted by the index of points forming the tetra. </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/home/runner/work/Open3D/Open3D/cpp/open3d/geometry/<a class="el" href="_tetra_mesh_8h_source.html">TetraMesh.h (9238339 (Tue Mar 14 18:49:09 2023 -0700))</a></li>
<li>/home/runner/work/Open3D/Open3D/cpp/open3d/geometry/<a class="el" href="_tetra_mesh_8cpp.html">TetraMesh.cpp (9238339 (Tue Mar 14 18:49:09 2023 -0700))</a></li>
<li>/home/runner/work/Open3D/Open3D/cpp/open3d/geometry/<a class="el" href="_tetra_mesh_factory_8cpp.html">TetraMeshFactory.cpp (9238339 (Tue Mar 14 18:49:09 2023 -0700))</a></li>
</ul>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>

<!-- Mirrored from www.open3d.org/docs/release/cpp_api/classopen3d_1_1geometry_1_1_tetra_mesh.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 14 May 2023 10:56:12 GMT -->
</html>
