<!-- HTML header for doxygen 1.8.20-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<!-- Mirrored from www.open3d.org/docs/release/cpp_api/classopen3d_1_1core_1_1_memory_manager.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 14 May 2023 10:55:17 GMT -->
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Open3D (C++ API): open3d::core::MemoryManager Class Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    extensions: ["tex2jax.js", "TeX/AMSmath.html", "TeX/AMSsymbols.js"],
    jax: ["input/TeX","output/HTML-CSS"],
});
</script>
<script type="text/javascript" async="async" src="../../../../cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-3TQPKGV6Z3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-3TQPKGV6Z3');
</script>
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectlogo"><img alt="Logo" src="open3d_logo.ico"/></td>
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Open3D (C++ API)
   &#160;<span id="projectnumber">0.17.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.html');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.html','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespaceopen3d.html">open3d</a></li><li class="navelem"><a class="el" href="namespaceopen3d_1_1core.html">core</a></li><li class="navelem"><a class="el" href="classopen3d_1_1core_1_1_memory_manager.3a6.d">MemoryManager</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-static-methods">Static Public Member Functions</a> &#124;
<a href="#pro-static-methods">Static Protected Member Functions</a>  </div>
  <div class="headertitle">
<div class="title">open3d::core::MemoryManager Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p><code>#include &lt;<a class="el" href="_memory_manager_8h_source.html">MemoryManager.h</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-static-methods"></a>
Static Public Member Functions</h2></td></tr>
<tr class="memitem:aa3908635804752f01a1f9377b22d0b09"><td class="memItemLeft" align="right" valign="top">static void *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1core_1_1_memory_manager.3a6.d#aa3908635804752f01a1f9377b22d0b09">Malloc</a> (size_t byte_size, const <a class="el" href="classopen3d_1_1core_1_1_device.html">Device</a> &amp;device)</td></tr>
<tr class="separator:aa3908635804752f01a1f9377b22d0b09"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae43870c863b2a038f08e2f5ae3227707"><td class="memItemLeft" align="right" valign="top">static void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1core_1_1_memory_manager.3a6.d#ae43870c863b2a038f08e2f5ae3227707">Free</a> (void *ptr, const <a class="el" href="classopen3d_1_1core_1_1_device.html">Device</a> &amp;device)</td></tr>
<tr class="memdesc:ae43870c863b2a038f08e2f5ae3227707"><td class="mdescLeft">&#160;</td><td class="mdescRight">Frees previously allocated memory at address <code>ptr</code> on device <code>device</code>.  <a href="classopen3d_1_1core_1_1_memory_manager.3a6.d#ae43870c863b2a038f08e2f5ae3227707">More...</a><br /></td></tr>
<tr class="separator:ae43870c863b2a038f08e2f5ae3227707"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a7230abfc96587869aa6a2d72d7363510"><td class="memItemLeft" align="right" valign="top">static void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1core_1_1_memory_manager.3a6.d#a7230abfc96587869aa6a2d72d7363510">Memcpy</a> (void *dst_ptr, const <a class="el" href="classopen3d_1_1core_1_1_device.html">Device</a> &amp;dst_device, const void *src_ptr, const <a class="el" href="classopen3d_1_1core_1_1_device.html">Device</a> &amp;src_device, size_t num_bytes)</td></tr>
<tr class="separator:a7230abfc96587869aa6a2d72d7363510"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a74921d92777e0fbdf559eb5bbbc9aa53"><td class="memItemLeft" align="right" valign="top">static void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1core_1_1_memory_manager.3a6.d#a74921d92777e0fbdf559eb5bbbc9aa53">MemcpyFromHost</a> (void *dst_ptr, const <a class="el" href="classopen3d_1_1core_1_1_device.html">Device</a> &amp;dst_device, const void *host_ptr, size_t num_bytes)</td></tr>
<tr class="memdesc:a74921d92777e0fbdf559eb5bbbc9aa53"><td class="mdescLeft">&#160;</td><td class="mdescRight">Same as Memcpy, but with host (CPU:0) as default src_device.  <a href="classopen3d_1_1core_1_1_memory_manager.3a6.d#a74921d92777e0fbdf559eb5bbbc9aa53">More...</a><br /></td></tr>
<tr class="separator:a74921d92777e0fbdf559eb5bbbc9aa53"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a12f4c6df82419dbe864b5880f3f8343d"><td class="memItemLeft" align="right" valign="top">static void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1core_1_1_memory_manager.3a6.d#a12f4c6df82419dbe864b5880f3f8343d">MemcpyToHost</a> (void *host_ptr, const void *src_ptr, const <a class="el" href="classopen3d_1_1core_1_1_device.html">Device</a> &amp;src_device, size_t num_bytes)</td></tr>
<tr class="memdesc:a12f4c6df82419dbe864b5880f3f8343d"><td class="mdescLeft">&#160;</td><td class="mdescRight">Same as Memcpy, but with host (CPU:0) as default dst_device.  <a href="classopen3d_1_1core_1_1_memory_manager.3a6.d#a12f4c6df82419dbe864b5880f3f8343d">More...</a><br /></td></tr>
<tr class="separator:a12f4c6df82419dbe864b5880f3f8343d"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pro-static-methods"></a>
Static Protected Member Functions</h2></td></tr>
<tr class="memitem:a494a4969de1ecbfbf5d7645416097ecd"><td class="memItemLeft" align="right" valign="top">static std::shared_ptr&lt; <a class="el" href="classopen3d_1_1core_1_1_memory_manager_devic">MemoryManagerDevice</a> &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1core_1_1_memory_manager.3a6.d#a494a4969de1ecbfbf5d7645416097ecd">GetMemoryManagerDevice</a> (const <a class="el" href="classopen3d_1_1core_1_1_device.html">Device</a> &amp;device)</td></tr>
<tr class="memdesc:a494a4969de1ecbfbf5d7645416097ecd"><td class="mdescLeft">&#160;</td><td class="mdescRight">Internally dispatches the appropriate <a class="el" href="classopen3d_1_1core_1_1_memory_manager_devic" title="Interface for all concrete memory manager classes.">MemoryManagerDevice</a> instance.  <a href="classopen3d_1_1core_1_1_memory_manager.3a6.d#a494a4969de1ecbfbf5d7645416097ecd">More...</a><br /></td></tr>
<tr class="separator:a494a4969de1ecbfbf5d7645416097ecd"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Top-level memory interface. Calls to any of the member functions will automatically dispatch the appropriate <a class="el" href="classopen3d_1_1core_1_1_memory_manager_devic" title="Interface for all concrete memory manager classes.">MemoryManagerDevice</a> instance based on the provided device which is used to execute the requested functionality.</p>
<p>The memory managers are dispatched as follows:</p>
<p>DeviceType = CPU : <a class="el" href="classopen3d_1_1core_1_1_memory_manager_c_p_u">MemoryManagerCPU</a> DeviceType = CUDA : ENABLE_CACHED_CUDA_MANAGER = ON : <a class="el" href="classopen3d_1_1core_1_1_memory_manager_cache">MemoryManagerCached</a> w/ MemoryManagerCUDA Otherwise : MemoryManagerCUDA </p>
</div><h2 class="groupheader">Member Function Documentation</h2>
<a id="ae43870c863b2a038f08e2f5ae3227707"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae43870c863b2a038f08e2f5ae3227707">&#9670;&nbsp;</a></span>Free()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void open3d::core::MemoryManager::Free </td>
          <td>(</td>
          <td class="paramtype">void *&#160;</td>
          <td class="paramname"><em>ptr</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const <a class="el" href="classopen3d_1_1core_1_1_device.html">Device</a> &amp;&#160;</td>
          <td class="paramname"><em>device</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Frees previously allocated memory at address <code>ptr</code> on device <code>device</code>. </p>

</div>
</div>
<a id="a494a4969de1ecbfbf5d7645416097ecd"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a494a4969de1ecbfbf5d7645416097ecd">&#9670;&nbsp;</a></span>GetMemoryManagerDevice()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">std::shared_ptr&lt; <a class="el" href="classopen3d_1_1core_1_1_memory_manager_devic">MemoryManagerDevice</a> &gt; open3d::core::MemoryManager::GetMemoryManagerDevice </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="classopen3d_1_1core_1_1_device.html">Device</a> &amp;&#160;</td>
          <td class="paramname"><em>device</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span><span class="mlabel">protected</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Internally dispatches the appropriate <a class="el" href="classopen3d_1_1core_1_1_memory_manager_devic" title="Interface for all concrete memory manager classes.">MemoryManagerDevice</a> instance. </p>

</div>
</div>
<a id="aa3908635804752f01a1f9377b22d0b09"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aa3908635804752f01a1f9377b22d0b09">&#9670;&nbsp;</a></span>Malloc()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void * open3d::core::MemoryManager::Malloc </td>
          <td>(</td>
          <td class="paramtype">size_t&#160;</td>
          <td class="paramname"><em>byte_size</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const <a class="el" href="classopen3d_1_1core_1_1_device.html">Device</a> &amp;&#160;</td>
          <td class="paramname"><em>device</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Allocates memory of <code>byte_size</code> bytes on device <code>device</code> and returns a pointer to the beginning of the allocated memory block. </p>

</div>
</div>
<a id="a7230abfc96587869aa6a2d72d7363510"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a7230abfc96587869aa6a2d72d7363510">&#9670;&nbsp;</a></span>Memcpy()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void open3d::core::MemoryManager::Memcpy </td>
          <td>(</td>
          <td class="paramtype">void *&#160;</td>
          <td class="paramname"><em>dst_ptr</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const <a class="el" href="classopen3d_1_1core_1_1_device.html">Device</a> &amp;&#160;</td>
          <td class="paramname"><em>dst_device</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const void *&#160;</td>
          <td class="paramname"><em>src_ptr</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const <a class="el" href="classopen3d_1_1core_1_1_device.html">Device</a> &amp;&#160;</td>
          <td class="paramname"><em>src_device</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">size_t&#160;</td>
          <td class="paramname"><em>num_bytes</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Copies <code>num_bytes</code> bytes of memory at address <code>src_ptr</code> on device <code>src_device</code> to address <code>dst_ptr</code> on device <code>dst_device</code>. </p>

</div>
</div>
<a id="a74921d92777e0fbdf559eb5bbbc9aa53"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a74921d92777e0fbdf559eb5bbbc9aa53">&#9670;&nbsp;</a></span>MemcpyFromHost()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void open3d::core::MemoryManager::MemcpyFromHost </td>
          <td>(</td>
          <td class="paramtype">void *&#160;</td>
          <td class="paramname"><em>dst_ptr</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const <a class="el" href="classopen3d_1_1core_1_1_device.html">Device</a> &amp;&#160;</td>
          <td class="paramname"><em>dst_device</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const void *&#160;</td>
          <td class="paramname"><em>host_ptr</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">size_t&#160;</td>
          <td class="paramname"><em>num_bytes</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Same as Memcpy, but with host (CPU:0) as default src_device. </p>

</div>
</div>
<a id="a12f4c6df82419dbe864b5880f3f8343d"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a12f4c6df82419dbe864b5880f3f8343d">&#9670;&nbsp;</a></span>MemcpyToHost()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void open3d::core::MemoryManager::MemcpyToHost </td>
          <td>(</td>
          <td class="paramtype">void *&#160;</td>
          <td class="paramname"><em>host_ptr</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const void *&#160;</td>
          <td class="paramname"><em>src_ptr</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const <a class="el" href="classopen3d_1_1core_1_1_device.html">Device</a> &amp;&#160;</td>
          <td class="paramname"><em>src_device</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">size_t&#160;</td>
          <td class="paramname"><em>num_bytes</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Same as Memcpy, but with host (CPU:0) as default dst_device. </p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>/home/runner/work/Open3D/Open3D/cpp/open3d/core/<a class="el" href="_memory_manager_8h_source.html">MemoryManager.h (9238339 (Tue Mar 14 18:49:09 2023 -0700))</a></li>
<li>/home/runner/work/Open3D/Open3D/cpp/open3d/core/<a class="el" href="_memory_manager_8cpp.html">MemoryManager.cpp (9238339 (Tue Mar 14 18:49:09 2023 -0700))</a></li>
</ul>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>

<!-- Mirrored from www.open3d.org/docs/release/cpp_api/classopen3d_1_1core_1_1_memory_manager.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 14 May 2023 10:55:18 GMT -->
</html>
