<!-- HTML header for doxygen 1.8.20-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<!-- Mirrored from www.open3d.org/docs/release/cpp_api/classopen3d_1_1io_1_1_r_g_b_d_recorder.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 14 May 2023 10:56:21 GMT -->
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Open3D (C++ API): open3d::io::RGBDRecorder Class Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    extensions: ["tex2jax.js", "TeX/AMSmath.html", "TeX/AMSsymbols.js"],
    jax: ["input/TeX","output/HTML-CSS"],
});
</script>
<script type="text/javascript" async="async" src="../../../../cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-3TQPKGV6Z3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-3TQPKGV6Z3');
</script>
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectlogo"><img alt="Logo" src="open3d_logo.ico"/></td>
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Open3D (C++ API)
   &#160;<span id="projectnumber">0.17.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.html');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.html','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespaceopen3d.html">open3d</a></li><li class="navelem"><a class="el" href="namespaceopen3d_1_1io.html">io</a></li><li class="navelem"><a class="el" href="classopen3d_1_1io_1_1_r_g_b_d_recorder.435.d">RGBDRecorder</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a>  </div>
  <div class="headertitle">
<div class="title">open3d::io::RGBDRecorder Class Reference<span class="mlabels"><span class="mlabel">abstract</span></span></div>  </div>
</div><!--header-->
<div class="contents">

<p><code>#include &lt;<a class="el" href="_r_g_b_d_recorder_8h_source.html">RGBDRecorder.h</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for open3d::io::RGBDRecorder:</div>
<div class="dyncontent">
 <div class="center">
  <img src="classopen3d_1_1io_1_1_r_g_b_d_recorder.66b.d" usemap="#open3d::io::RGBDRecorder_map" alt=""/>
  <map id="open3d::io::RGBDRecorder_map" name="open3d::io::RGBDRecorder_map">
<area href="classopen3d_1_1io_1_1_azure_kinect_recorder" alt="open3d::io::AzureKinectRecorder" shape="rect" coords="0,56,198,80"/>
  </map>
</div></div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a5fb1c4751b0d3479818a26d1ccaa1724"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1io_1_1_r_g_b_d_recorder.435.d#a5fb1c4751b0d3479818a26d1ccaa1724">RGBDRecorder</a> ()</td></tr>
<tr class="separator:a5fb1c4751b0d3479818a26d1ccaa1724"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae8ed400e7ae7ba1a9047fbad7fe6b161"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1io_1_1_r_g_b_d_recorder.435.d#ae8ed400e7ae7ba1a9047fbad7fe6b161">~RGBDRecorder</a> ()</td></tr>
<tr class="separator:ae8ed400e7ae7ba1a9047fbad7fe6b161"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ac907644f05991f5eb51902a27930bf84"><td class="memItemLeft" align="right" valign="top">virtual bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1io_1_1_r_g_b_d_recorder.435.d#ac907644f05991f5eb51902a27930bf84">InitSensor</a> ()=0</td></tr>
<tr class="memdesc:ac907644f05991f5eb51902a27930bf84"><td class="mdescLeft">&#160;</td><td class="mdescRight">Init recorder, connect to sensor.  <a href="classopen3d_1_1io_1_1_r_g_b_d_recorder.435.d#ac907644f05991f5eb51902a27930bf84">More...</a><br /></td></tr>
<tr class="separator:ac907644f05991f5eb51902a27930bf84"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad045fe367097f8753101ae0bbc2f83ce"><td class="memItemLeft" align="right" valign="top">virtual bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1io_1_1_r_g_b_d_recorder.435.d#ad045fe367097f8753101ae0bbc2f83ce">OpenRecord</a> (const std::string &amp;filename)=0</td></tr>
<tr class="memdesc:ad045fe367097f8753101ae0bbc2f83ce"><td class="mdescLeft">&#160;</td><td class="mdescRight">Create recording file.  <a href="classopen3d_1_1io_1_1_r_g_b_d_recorder.435.d#ad045fe367097f8753101ae0bbc2f83ce">More...</a><br /></td></tr>
<tr class="separator:ad045fe367097f8753101ae0bbc2f83ce"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a52df93cdd56a46f2440f3e6a4dcc0e39"><td class="memItemLeft" align="right" valign="top">virtual std::shared_ptr&lt; <a class="el" href="classopen3d_1_1geometry_1_1_r_g_b_d_image.37">geometry::RGBDImage</a> &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1io_1_1_r_g_b_d_recorder.435.d#a52df93cdd56a46f2440f3e6a4dcc0e39">RecordFrame</a> (bool write, bool enable_align_depth_to_color)=0</td></tr>
<tr class="separator:a52df93cdd56a46f2440f3e6a4dcc0e39"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a61c36228d5c4a463b15d8b8bc6e5e500"><td class="memItemLeft" align="right" valign="top">virtual bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1io_1_1_r_g_b_d_recorder.435.d#a61c36228d5c4a463b15d8b8bc6e5e500">CloseRecord</a> ()=0</td></tr>
<tr class="memdesc:a61c36228d5c4a463b15d8b8bc6e5e500"><td class="mdescLeft">&#160;</td><td class="mdescRight">Flush data to recording file and disconnect from sensor.  <a href="classopen3d_1_1io_1_1_r_g_b_d_recorder.435.d#a61c36228d5c4a463b15d8b8bc6e5e500">More...</a><br /></td></tr>
<tr class="separator:a61c36228d5c4a463b15d8b8bc6e5e500"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a id="a5fb1c4751b0d3479818a26d1ccaa1724"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a5fb1c4751b0d3479818a26d1ccaa1724">&#9670;&nbsp;</a></span>RGBDRecorder()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">open3d::io::RGBDRecorder::RGBDRecorder </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="ae8ed400e7ae7ba1a9047fbad7fe6b161"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae8ed400e7ae7ba1a9047fbad7fe6b161">&#9670;&nbsp;</a></span>~RGBDRecorder()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual open3d::io::RGBDRecorder::~RGBDRecorder </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a id="a61c36228d5c4a463b15d8b8bc6e5e500"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a61c36228d5c4a463b15d8b8bc6e5e500">&#9670;&nbsp;</a></span>CloseRecord()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual bool open3d::io::RGBDRecorder::CloseRecord </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">pure virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Flush data to recording file and disconnect from sensor. </p>

<p>Implemented in <a class="el" href="classopen3d_1_1io_1_1_azure_kinect_recorder#a8ab07f392624def817226926414da800">open3d::io::AzureKinectRecorder</a>.</p>

</div>
</div>
<a id="ac907644f05991f5eb51902a27930bf84"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ac907644f05991f5eb51902a27930bf84">&#9670;&nbsp;</a></span>InitSensor()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual bool open3d::io::RGBDRecorder::InitSensor </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">pure virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Init recorder, connect to sensor. </p>

<p>Implemented in <a class="el" href="classopen3d_1_1io_1_1_azure_kinect_recorder#a314e691cea43479b753e86813b5c3922">open3d::io::AzureKinectRecorder</a>.</p>

</div>
</div>
<a id="ad045fe367097f8753101ae0bbc2f83ce"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ad045fe367097f8753101ae0bbc2f83ce">&#9670;&nbsp;</a></span>OpenRecord()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual bool open3d::io::RGBDRecorder::OpenRecord </td>
          <td>(</td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>filename</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">pure virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Create recording file. </p>

<p>Implemented in <a class="el" href="classopen3d_1_1io_1_1_azure_kinect_recorder#a573d1ef8b0e6a3ad764cd5b7b7b3aeb5">open3d::io::AzureKinectRecorder</a>.</p>

</div>
</div>
<a id="a52df93cdd56a46f2440f3e6a4dcc0e39"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a52df93cdd56a46f2440f3e6a4dcc0e39">&#9670;&nbsp;</a></span>RecordFrame()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">virtual std::shared_ptr&lt;<a class="el" href="classopen3d_1_1geometry_1_1_r_g_b_d_image.37">geometry::RGBDImage</a>&gt; open3d::io::RGBDRecorder::RecordFrame </td>
          <td>(</td>
          <td class="paramtype">bool&#160;</td>
          <td class="paramname"><em>write</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">bool&#160;</td>
          <td class="paramname"><em>enable_align_depth_to_color</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">pure virtual</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">
<p>Record one frame, return an RGBDImage. If <code>write</code> is true, the RGBDImage frame will be written to file. If <code>enable_align_depth_to_color</code> is true, the depth image will be warped to align with the color image; otherwise the raw depth image output will be saved. Setting <code>enable_align_depth_to_color</code> to false is useful when recording at high resolution with high frame rates. In this case, the depth image must be warped to align with the color image with when reading from the recorded file. </p>

<p>Implemented in <a class="el" href="classopen3d_1_1io_1_1_azure_kinect_recorder#a723b819b0846dbb0d19edaf39b9d2112">open3d::io::AzureKinectRecorder</a>.</p>

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/home/runner/work/Open3D/Open3D/cpp/open3d/io/sensor/<a class="el" href="_r_g_b_d_recorder_8h_source.html">RGBDRecorder.h (9238339 (Tue Mar 14 18:49:09 2023 -0700))</a></li>
</ul>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>

<!-- Mirrored from www.open3d.org/docs/release/cpp_api/classopen3d_1_1io_1_1_r_g_b_d_recorder.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 14 May 2023 10:56:21 GMT -->
</html>
