<!-- HTML header for doxygen 1.8.20-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<!-- Mirrored from www.open3d.org/docs/release/cpp_api/classopen3d_1_1t_1_1io_1_1_numpy_array.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 14 May 2023 10:53:38 GMT -->
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Open3D (C++ API): open3d::t::io::NumpyArray Class Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    extensions: ["tex2jax.js", "TeX/AMSmath.html", "TeX/AMSsymbols.js"],
    jax: ["input/TeX","output/HTML-CSS"],
});
</script>
<script type="text/javascript" async="async" src="../../../../cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-3TQPKGV6Z3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-3TQPKGV6Z3');
</script>
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectlogo"><img alt="Logo" src="open3d_logo.ico"/></td>
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Open3D (C++ API)
   &#160;<span id="projectnumber">0.17.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.html');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.html','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespaceopen3d.html">open3d</a></li><li class="navelem"><a class="el" href="namespaceopen3d_1_1t.html">t</a></li><li class="navelem"><a class="el" href="namespaceopen3d_1_1t_1_1io.html">io</a></li><li class="navelem"><a class="el" href="classopen3d_1_1t_1_1io_1_1_numpy_array.347.d">NumpyArray</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a>  </div>
  <div class="headertitle">
<div class="title">open3d::t::io::NumpyArray Class Reference</div>  </div>
</div><!--header-->
<div class="contents">
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:aa4a1ba58cd4abddc8a3796773c888e48"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1t_1_1io_1_1_numpy_array.347.d#aa4a1ba58cd4abddc8a3796773c888e48">NumpyArray</a> (const <a class="el" href="classopen3d_1_1core_1_1_tensor.html">core::Tensor</a> &amp;t)</td></tr>
<tr class="separator:aa4a1ba58cd4abddc8a3796773c888e48"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9afc326582bab28e756de7c92ea6fb81"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1t_1_1io_1_1_numpy_array.347.d#a9afc326582bab28e756de7c92ea6fb81">NumpyArray</a> (const <a class="el" href="classopen3d_1_1core_1_1_size_vector.3b3.dela">core::SizeVector</a> &amp;shape, char <a class="el" href="io_2file__format_2_file_p_c_d_8cpp.375.delay#aff17911edc8208aa8ddb1c7c52c78389">type</a>, int64_t word_size, bool fortran_order)</td></tr>
<tr class="separator:a9afc326582bab28e756de7c92ea6fb81"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aaf2bed1e70f7f127b3aa70ec32f2b218"><td class="memTemplParams" colspan="2">template&lt;typename T &gt; </td></tr>
<tr class="memitem:aaf2bed1e70f7f127b3aa70ec32f2b218"><td class="memTemplItemLeft" align="right" valign="top">T *&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="classopen3d_1_1t_1_1io_1_1_numpy_array.347.d#aaf2bed1e70f7f127b3aa70ec32f2b218">GetDataPtr</a> ()</td></tr>
<tr class="separator:aaf2bed1e70f7f127b3aa70ec32f2b218"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a041b8149a1ebeaa11badb529ae378780"><td class="memTemplParams" colspan="2">template&lt;typename T &gt; </td></tr>
<tr class="memitem:a041b8149a1ebeaa11badb529ae378780"><td class="memTemplItemLeft" align="right" valign="top">const T *&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="classopen3d_1_1t_1_1io_1_1_numpy_array.347.d#a041b8149a1ebeaa11badb529ae378780">GetDataPtr</a> () const</td></tr>
<tr class="separator:a041b8149a1ebeaa11badb529ae378780"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a86cc8154db11eb0b38c136cdb7411ec1"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classopen3d_1_1core_1_1_dtype.html">core::Dtype</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1t_1_1io_1_1_numpy_array.347.d#a86cc8154db11eb0b38c136cdb7411ec1">GetDtype</a> () const</td></tr>
<tr class="separator:a86cc8154db11eb0b38c136cdb7411ec1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aacf980c5eab11327baaa455bc7d9a8ca"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classopen3d_1_1core_1_1_size_vector.3b3.dela">core::SizeVector</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1t_1_1io_1_1_numpy_array.347.d#aacf980c5eab11327baaa455bc7d9a8ca">GetShape</a> () const</td></tr>
<tr class="separator:aacf980c5eab11327baaa455bc7d9a8ca"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5263f34be4bd63852fdcc893f62ac750"><td class="memItemLeft" align="right" valign="top">bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1t_1_1io_1_1_numpy_array.347.d#a5263f34be4bd63852fdcc893f62ac750">IsFortranOrder</a> () const</td></tr>
<tr class="separator:a5263f34be4bd63852fdcc893f62ac750"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0e2632f3abb7a967af540030467c62db"><td class="memItemLeft" align="right" valign="top">int64_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1t_1_1io_1_1_numpy_array.347.d#a0e2632f3abb7a967af540030467c62db">NumBytes</a> () const</td></tr>
<tr class="separator:a0e2632f3abb7a967af540030467c62db"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a1e8e279e72657ca6d4d9e511903014ee"><td class="memItemLeft" align="right" valign="top">int64_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1t_1_1io_1_1_numpy_array.347.d#a1e8e279e72657ca6d4d9e511903014ee">NumElements</a> () const</td></tr>
<tr class="separator:a1e8e279e72657ca6d4d9e511903014ee"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adee770715cc74a6bd0196fbdc2edb593"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classopen3d_1_1core_1_1_tensor.html">core::Tensor</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1t_1_1io_1_1_numpy_array.347.d#adee770715cc74a6bd0196fbdc2edb593">ToTensor</a> () const</td></tr>
<tr class="separator:adee770715cc74a6bd0196fbdc2edb593"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae4cc2d7afd19e0983f0aadb296422462"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1t_1_1io_1_1_numpy_array.347.d#ae4cc2d7afd19e0983f0aadb296422462">Save</a> (std::string file_name) const</td></tr>
<tr class="separator:ae4cc2d7afd19e0983f0aadb296422462"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a id="aa4a1ba58cd4abddc8a3796773c888e48"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aa4a1ba58cd4abddc8a3796773c888e48">&#9670;&nbsp;</a></span>NumpyArray() <span class="overload">[1/2]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">open3d::t::io::NumpyArray::NumpyArray </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="classopen3d_1_1core_1_1_tensor.html">core::Tensor</a> &amp;&#160;</td>
          <td class="paramname"><em>t</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a9afc326582bab28e756de7c92ea6fb81"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a9afc326582bab28e756de7c92ea6fb81">&#9670;&nbsp;</a></span>NumpyArray() <span class="overload">[2/2]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">open3d::t::io::NumpyArray::NumpyArray </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="classopen3d_1_1core_1_1_size_vector.3b3.dela">core::SizeVector</a> &amp;&#160;</td>
          <td class="paramname"><em>shape</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">char&#160;</td>
          <td class="paramname"><em>type</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int64_t&#160;</td>
          <td class="paramname"><em>word_size</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">bool&#160;</td>
          <td class="paramname"><em>fortran_order</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a id="aaf2bed1e70f7f127b3aa70ec32f2b218"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aaf2bed1e70f7f127b3aa70ec32f2b218">&#9670;&nbsp;</a></span>GetDataPtr() <span class="overload">[1/2]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;typename T &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">T* open3d::t::io::NumpyArray::GetDataPtr </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a041b8149a1ebeaa11badb529ae378780"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a041b8149a1ebeaa11badb529ae378780">&#9670;&nbsp;</a></span>GetDataPtr() <span class="overload">[2/2]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;typename T &gt; </div>
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">const T* open3d::t::io::NumpyArray::GetDataPtr </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a86cc8154db11eb0b38c136cdb7411ec1"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a86cc8154db11eb0b38c136cdb7411ec1">&#9670;&nbsp;</a></span>GetDtype()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classopen3d_1_1core_1_1_dtype.html">core::Dtype</a> open3d::t::io::NumpyArray::GetDtype </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="aacf980c5eab11327baaa455bc7d9a8ca"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aacf980c5eab11327baaa455bc7d9a8ca">&#9670;&nbsp;</a></span>GetShape()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classopen3d_1_1core_1_1_size_vector.3b3.dela">core::SizeVector</a> open3d::t::io::NumpyArray::GetShape </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a5263f34be4bd63852fdcc893f62ac750"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a5263f34be4bd63852fdcc893f62ac750">&#9670;&nbsp;</a></span>IsFortranOrder()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">bool open3d::t::io::NumpyArray::IsFortranOrder </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a0e2632f3abb7a967af540030467c62db"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a0e2632f3abb7a967af540030467c62db">&#9670;&nbsp;</a></span>NumBytes()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">int64_t open3d::t::io::NumpyArray::NumBytes </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a1e8e279e72657ca6d4d9e511903014ee"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a1e8e279e72657ca6d4d9e511903014ee">&#9670;&nbsp;</a></span>NumElements()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">int64_t open3d::t::io::NumpyArray::NumElements </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="ae4cc2d7afd19e0983f0aadb296422462"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae4cc2d7afd19e0983f0aadb296422462">&#9670;&nbsp;</a></span>Save()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void open3d::t::io::NumpyArray::Save </td>
          <td>(</td>
          <td class="paramtype">std::string&#160;</td>
          <td class="paramname"><em>file_name</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="adee770715cc74a6bd0196fbdc2edb593"></a>
<h2 class="memtitle"><span class="permalink"><a href="#adee770715cc74a6bd0196fbdc2edb593">&#9670;&nbsp;</a></span>ToTensor()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classopen3d_1_1core_1_1_tensor.html">core::Tensor</a> open3d::t::io::NumpyArray::ToTensor </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<hr/>The documentation for this class was generated from the following file:<ul>
<li>/home/runner/work/Open3D/Open3D/cpp/open3d/t/io/<a class="el" href="_numpy_i_o_8cpp.html">NumpyIO.cpp (9238339 (Tue Mar 14 18:49:09 2023 -0700))</a></li>
</ul>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>

<!-- Mirrored from www.open3d.org/docs/release/cpp_api/classopen3d_1_1t_1_1io_1_1_numpy_array.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 14 May 2023 10:53:38 GMT -->
</html>
