<!-- HTML header for doxygen 1.8.20-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<!-- Mirrored from www.open3d.org/docs/release/cpp_api/namespaceopen3d_1_1geometry_1_1poisson.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 14 May 2023 10:55:52 GMT -->
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Open3D (C++ API): open3d::geometry::poisson Namespace Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    extensions: ["tex2jax.js", "TeX/AMSmath.html", "TeX/AMSsymbols.js"],
    jax: ["input/TeX","output/HTML-CSS"],
});
</script>
<script type="text/javascript" async="async" src="../../../../cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-3TQPKGV6Z3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-3TQPKGV6Z3');
</script>
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectlogo"><img alt="Logo" src="open3d_logo.ico"/></td>
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Open3D (C++ API)
   &#160;<span id="projectnumber">0.17.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.html');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.html','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespaceopen3d.html">open3d</a></li><li class="navelem"><a class="el" href="namespaceopen3d_1_1geometry.html">geometry</a></li><li class="navelem"><a class="el" href="namespaceopen3d_1_1geometry_1_1poisson.3fd.d">poisson</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#nested-classes">Data Structures</a> &#124;
<a href="#func-members">Functions</a>  </div>
  <div class="headertitle">
<div class="title">open3d::geometry::poisson Namespace Reference</div>  </div>
</div><!--header-->
<div class="contents">
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Data Structures</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1poisson_1_1_open3">Open3DData</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1poisson_1_1_open3-2">Open3DPointStream</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classopen3d_1_1geometry_1_1poisson_1_1_open3-3">Open3DVertex</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">struct &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="structopen3d_1_1geometry_1_1poisson_1_1_f_e_">FEMTreeProfiler</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">struct &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="structopen3d_1_1geometry_1_1poisson_1_1_cons">ConstraintDual</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">struct &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="structopen3d_1_1geometry_1_1poisson_1_1_syst">SystemDual</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">struct &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="structopen3d_1_1geometry_1_1poisson_1_1_syst-2">SystemDual&lt; Dim, double &gt;</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a0764741386e4c522d7b9cbb4b67344b2"><td class="memTemplParams" colspan="2">template&lt;class Real , unsigned int Dim&gt; </td></tr>
<tr class="memitem:a0764741386e4c522d7b9cbb4b67344b2"><td class="memTemplItemLeft" align="right" valign="top">XForm&lt; Real, Dim+1 &gt;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="namespaceopen3d_1_1geometry_1_1poisson.3fd.d#a0764741386e4c522d7b9cbb4b67344b2">GetBoundingBoxXForm</a> (Point&lt; Real, Dim &gt; min, Point&lt; Real, Dim &gt; max, Real scaleFactor)</td></tr>
<tr class="separator:a0764741386e4c522d7b9cbb4b67344b2"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa87dccb1494ea0651ee133ba8b379969"><td class="memTemplParams" colspan="2">template&lt;class Real , unsigned int Dim&gt; </td></tr>
<tr class="memitem:aa87dccb1494ea0651ee133ba8b379969"><td class="memTemplItemLeft" align="right" valign="top">XForm&lt; Real, Dim+1 &gt;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="namespaceopen3d_1_1geometry_1_1poisson.3fd.d#aa87dccb1494ea0651ee133ba8b379969">GetBoundingBoxXForm</a> (Point&lt; Real, Dim &gt; min, Point&lt; Real, Dim &gt; max, Real <a class="el" href="io_2file__format_2_file_p_c_d_8cpp.375.delay#a2474a5474cbff19523a51eb1de01cda4">width</a>, Real scaleFactor, int &amp;depth)</td></tr>
<tr class="separator:aa87dccb1494ea0651ee133ba8b379969"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3fae8d2f4abbced63e69215d27c7079d"><td class="memTemplParams" colspan="2">template&lt;class Real , unsigned int Dim&gt; </td></tr>
<tr class="memitem:a3fae8d2f4abbced63e69215d27c7079d"><td class="memTemplItemLeft" align="right" valign="top">XForm&lt; Real, Dim+1 &gt;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="namespaceopen3d_1_1geometry_1_1poisson.3fd.d#a3fae8d2f4abbced63e69215d27c7079d">GetPointXForm</a> (InputPointStream&lt; Real, Dim &gt; &amp;stream, Real <a class="el" href="io_2file__format_2_file_p_c_d_8cpp.375.delay#a2474a5474cbff19523a51eb1de01cda4">width</a>, Real scaleFactor, int &amp;depth)</td></tr>
<tr class="separator:a3fae8d2f4abbced63e69215d27c7079d"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a43fa884e63d19c4a801764b2b0e9fbf9"><td class="memTemplParams" colspan="2">template&lt;class Real , unsigned int Dim&gt; </td></tr>
<tr class="memitem:a43fa884e63d19c4a801764b2b0e9fbf9"><td class="memTemplItemLeft" align="right" valign="top">XForm&lt; Real, Dim+1 &gt;&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="namespaceopen3d_1_1geometry_1_1poisson.3fd.d#a43fa884e63d19c4a801764b2b0e9fbf9">GetPointXForm</a> (InputPointStream&lt; Real, Dim &gt; &amp;stream, Real scaleFactor)</td></tr>
<tr class="separator:a43fa884e63d19c4a801764b2b0e9fbf9"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a579147ea392a341c874046f2c8a77151"><td class="memTemplParams" colspan="2">template&lt;typename Vertex , typename Real , typename SetVertexFunction , unsigned int... FEMSigs, typename... SampleData&gt; </td></tr>
<tr class="memitem:a579147ea392a341c874046f2c8a77151"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="namespaceopen3d_1_1geometry_1_1poisson.3fd.d#a579147ea392a341c874046f2c8a77151">ExtractMesh</a> (float datax, bool linear_fit, UIntPack&lt; FEMSigs... &gt;, std::tuple&lt; SampleData... &gt;, FEMTree&lt; sizeof...(FEMSigs), Real &gt; &amp;tree, const DenseNodeData&lt; Real, UIntPack&lt; FEMSigs... &gt;&gt; &amp;solution, Real isoValue, const std::vector&lt; typename FEMTree&lt; sizeof...(FEMSigs), Real &gt;::PointSample &gt; *samples, std::vector&lt; <a class="el" href="classopen3d_1_1geometry_1_1poisson_1_1_open3">Open3DData</a> &gt; *sampleData, const typename FEMTree&lt; sizeof...(FEMSigs), Real &gt;::template DensityEstimator&lt; WEIGHT_DEGREE &gt; *density, const SetVertexFunction &amp;SetVertex, XForm&lt; Real, sizeof...(FEMSigs)+1 &gt; iXForm, std::shared_ptr&lt; <a class="el" href="classopen3d_1_1geometry_1_1_triangle_mesh.40">open3d::geometry::TriangleMesh</a> &gt; &amp;out_mesh, std::vector&lt; double &gt; &amp;out_densities)</td></tr>
<tr class="separator:a579147ea392a341c874046f2c8a77151"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad268ca17c86be6593994daa68a2f487e"><td class="memTemplParams" colspan="2">template&lt;class Real , typename... SampleData, unsigned int... FEMSigs&gt; </td></tr>
<tr class="memitem:ad268ca17c86be6593994daa68a2f487e"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="namespaceopen3d_1_1geometry_1_1poisson.3fd.d#ad268ca17c86be6593994daa68a2f487e">Execute</a> (const <a class="el" href="classopen3d_1_1geometry_1_1_point_cloud.41b">open3d::geometry::PointCloud</a> &amp;pcd, std::shared_ptr&lt; <a class="el" href="classopen3d_1_1geometry_1_1_triangle_mesh.40">open3d::geometry::TriangleMesh</a> &gt; &amp;out_mesh, std::vector&lt; double &gt; &amp;out_densities, int depth, float <a class="el" href="io_2file__format_2_file_p_c_d_8cpp.375.delay#a2474a5474cbff19523a51eb1de01cda4">width</a>, float scale, bool linear_fit, UIntPack&lt; FEMSigs... &gt;)</td></tr>
<tr class="separator:ad268ca17c86be6593994daa68a2f487e"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Function Documentation</h2>
<a id="ad268ca17c86be6593994daa68a2f487e"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ad268ca17c86be6593994daa68a2f487e">&#9670;&nbsp;</a></span>Execute()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class Real , typename... SampleData, unsigned int... FEMSigs&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void open3d::geometry::poisson::Execute </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="classopen3d_1_1geometry_1_1_point_cloud.41b">open3d::geometry::PointCloud</a> &amp;&#160;</td>
          <td class="paramname"><em>pcd</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">std::shared_ptr&lt; <a class="el" href="classopen3d_1_1geometry_1_1_triangle_mesh.40">open3d::geometry::TriangleMesh</a> &gt; &amp;&#160;</td>
          <td class="paramname"><em>out_mesh</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">std::vector&lt; double &gt; &amp;&#160;</td>
          <td class="paramname"><em>out_densities</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>depth</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">float&#160;</td>
          <td class="paramname"><em>width</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">float&#160;</td>
          <td class="paramname"><em>scale</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">bool&#160;</td>
          <td class="paramname"><em>linear_fit</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">UIntPack&lt; FEMSigs... &gt;&#160;</td>
          <td class="paramname">&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a579147ea392a341c874046f2c8a77151"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a579147ea392a341c874046f2c8a77151">&#9670;&nbsp;</a></span>ExtractMesh()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;typename Vertex , typename Real , typename SetVertexFunction , unsigned int... FEMSigs, typename... SampleData&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void open3d::geometry::poisson::ExtractMesh </td>
          <td>(</td>
          <td class="paramtype">float&#160;</td>
          <td class="paramname"><em>datax</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">bool&#160;</td>
          <td class="paramname"><em>linear_fit</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">UIntPack&lt; FEMSigs... &gt;&#160;</td>
          <td class="paramname">, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">std::tuple&lt; SampleData... &gt;&#160;</td>
          <td class="paramname">, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">FEMTree&lt; sizeof...(FEMSigs), Real &gt; &amp;&#160;</td>
          <td class="paramname"><em>tree</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const DenseNodeData&lt; Real, UIntPack&lt; FEMSigs... &gt;&gt; &amp;&#160;</td>
          <td class="paramname"><em>solution</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Real&#160;</td>
          <td class="paramname"><em>isoValue</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const std::vector&lt; typename FEMTree&lt; sizeof...(FEMSigs), Real &gt;::PointSample &gt; *&#160;</td>
          <td class="paramname"><em>samples</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">std::vector&lt; <a class="el" href="classopen3d_1_1geometry_1_1poisson_1_1_open3">Open3DData</a> &gt; *&#160;</td>
          <td class="paramname"><em>sampleData</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const typename FEMTree&lt; sizeof...(FEMSigs), Real &gt;::template DensityEstimator&lt; WEIGHT_DEGREE &gt; *&#160;</td>
          <td class="paramname"><em>density</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const SetVertexFunction &amp;&#160;</td>
          <td class="paramname"><em>SetVertex</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">XForm&lt; Real, sizeof...(FEMSigs)+1 &gt;&#160;</td>
          <td class="paramname"><em>iXForm</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">std::shared_ptr&lt; <a class="el" href="classopen3d_1_1geometry_1_1_triangle_mesh.40">open3d::geometry::TriangleMesh</a> &gt; &amp;&#160;</td>
          <td class="paramname"><em>out_mesh</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">std::vector&lt; double &gt; &amp;&#160;</td>
          <td class="paramname"><em>out_densities</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a0764741386e4c522d7b9cbb4b67344b2"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a0764741386e4c522d7b9cbb4b67344b2">&#9670;&nbsp;</a></span>GetBoundingBoxXForm() <span class="overload">[1/2]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class Real , unsigned int Dim&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">XForm&lt;Real, Dim + 1&gt; open3d::geometry::poisson::GetBoundingBoxXForm </td>
          <td>(</td>
          <td class="paramtype">Point&lt; Real, Dim &gt;&#160;</td>
          <td class="paramname"><em>min</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Point&lt; Real, Dim &gt;&#160;</td>
          <td class="paramname"><em>max</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Real&#160;</td>
          <td class="paramname"><em>scaleFactor</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="aa87dccb1494ea0651ee133ba8b379969"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aa87dccb1494ea0651ee133ba8b379969">&#9670;&nbsp;</a></span>GetBoundingBoxXForm() <span class="overload">[2/2]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class Real , unsigned int Dim&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">XForm&lt;Real, Dim + 1&gt; open3d::geometry::poisson::GetBoundingBoxXForm </td>
          <td>(</td>
          <td class="paramtype">Point&lt; Real, Dim &gt;&#160;</td>
          <td class="paramname"><em>min</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Point&lt; Real, Dim &gt;&#160;</td>
          <td class="paramname"><em>max</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Real&#160;</td>
          <td class="paramname"><em>width</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Real&#160;</td>
          <td class="paramname"><em>scaleFactor</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int &amp;&#160;</td>
          <td class="paramname"><em>depth</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a43fa884e63d19c4a801764b2b0e9fbf9"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a43fa884e63d19c4a801764b2b0e9fbf9">&#9670;&nbsp;</a></span>GetPointXForm() <span class="overload">[1/2]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class Real , unsigned int Dim&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">XForm&lt;Real, Dim + 1&gt; open3d::geometry::poisson::GetPointXForm </td>
          <td>(</td>
          <td class="paramtype">InputPointStream&lt; Real, Dim &gt; &amp;&#160;</td>
          <td class="paramname"><em>stream</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Real&#160;</td>
          <td class="paramname"><em>scaleFactor</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a3fae8d2f4abbced63e69215d27c7079d"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a3fae8d2f4abbced63e69215d27c7079d">&#9670;&nbsp;</a></span>GetPointXForm() <span class="overload">[2/2]</span></h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class Real , unsigned int Dim&gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">XForm&lt;Real, Dim + 1&gt; open3d::geometry::poisson::GetPointXForm </td>
          <td>(</td>
          <td class="paramtype">InputPointStream&lt; Real, Dim &gt; &amp;&#160;</td>
          <td class="paramname"><em>stream</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Real&#160;</td>
          <td class="paramname"><em>width</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">Real&#160;</td>
          <td class="paramname"><em>scaleFactor</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">int &amp;&#160;</td>
          <td class="paramname"><em>depth</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>

<!-- Mirrored from www.open3d.org/docs/release/cpp_api/namespaceopen3d_1_1geometry_1_1poisson.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 14 May 2023 10:55:52 GMT -->
</html>
