<!-- HTML header for doxygen 1.8.20-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<!-- Mirrored from www.open3d.org/docs/release/cpp_api/pytorch_2misc_2_radius_search_ops_8cpp.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 14 May 2023 11:04:58 GMT -->
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Open3D (C++ API): /home/runner/work/Open3D/Open3D/cpp/open3d/ml/pytorch/misc/RadiusSearchOps.cpp File Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    extensions: ["tex2jax.js", "TeX/AMSmath.html", "TeX/AMSsymbols.js"],
    jax: ["input/TeX","output/HTML-CSS"],
});
</script>
<script type="text/javascript" async="async" src="../../../../cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-3TQPKGV6Z3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-3TQPKGV6Z3');
</script>
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectlogo"><img alt="Logo" src="open3d_logo.ico"/></td>
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Open3D (C++ API)
   &#160;<span id="projectnumber">0.17.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.html');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.html','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_df511e5bd85cec96854b39d5e1c27aa8.357.del">cpp</a></li><li class="navelem"><a class="el" href="dir_f8cc15b2217ff526bd336cf17635da2a.358.del">open3d</a></li><li class="navelem"><a class="el" href="dir_b383250e6a9804e003b118f7109c729e.4d9.del">ml</a></li><li class="navelem"><a class="el" href="dir_1811a8209f8e715bc8a18e4feda91876.8e9.del">pytorch</a></li><li class="navelem"><a class="el" href="dir_f195b792b3849e3339f1e297afbbd646.c14.del">misc</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#define-members">Macros</a> &#124;
<a href="#func-members">Functions</a> &#124;
<a href="#var-members">Variables</a>  </div>
  <div class="headertitle">
<div class="title">RadiusSearchOps.cpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<h3 class="version">(9238339 (Tue Mar 14 18:49:09 2023 -0700))</h3><div class="textblock"><code>#include &lt;vector&gt;</code><br />
<code>#include &quot;<a class="el" href="_dtype_8h_source.html">open3d/core/Dtype.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="core_2nns_2_neighbor_search_common_8h_source">open3d/core/nns/NeighborSearchCommon.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="_torch_helper_8h_source.html">open3d/ml/pytorch/TorchHelper.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="utility_2_helper_8h_source.html">open3d/utility/Helper.h</a>&quot;</code><br />
<code>#include &quot;torch/script.h&quot;</code><br />
</div><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="define-members"></a>
Macros</h2></td></tr>
<tr class="memitem:a5bca80bb5cc651b5b0c11faceb94497f"><td class="memItemLeft" align="right" valign="top">#define&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="pytorch_2misc_2_radius_search_ops_8cpp.d06.d#a5bca80bb5cc651b5b0c11faceb94497f">FN_PARAMETERS</a></td></tr>
<tr class="separator:a5bca80bb5cc651b5b0c11faceb94497f"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a5c53ee008516ea096adece570b14458e"><td class="memTemplParams" colspan="2">template&lt;class T , class TIndex &gt; </td></tr>
<tr class="memitem:a5c53ee008516ea096adece570b14458e"><td class="memTemplItemLeft" align="right" valign="top">void&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="pytorch_2misc_2_radius_search_ops_8cpp.d06.d#a5c53ee008516ea096adece570b14458e">RadiusSearchCPU</a> (const torch::Tensor &amp;<a class="el" href="io_2file__format_2_file_p_c_d_8cpp.375.delay#af7f8f4a4e39e09fdb5e9f02330ecabef">points</a>, const torch::Tensor &amp;queries, const torch::Tensor &amp;radii, const torch::Tensor &amp;points_row_splits, const torch::Tensor &amp;queries_row_splits, const <a class="el" href="namespaceopen3d_1_1core_1_1nns.html#a1ee06f6e576842e4122fded5bab8b074">Metric</a> metric, const bool ignore_query_point, const bool return_distances, const bool normalize_distances, torch::Tensor &amp;neighbors_index, torch::Tensor &amp;neighbors_row_splits, torch::Tensor &amp;neighbors_distance)</td></tr>
<tr class="separator:a5c53ee008516ea096adece570b14458e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae6b0b2000f143e707c504b821f570dcc"><td class="memItemLeft" align="right" valign="top">std::tuple&lt; torch::Tensor, torch::Tensor, torch::Tensor &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="pytorch_2misc_2_radius_search_ops_8cpp.d06.d#ae6b0b2000f143e707c504b821f570dcc">MultiRadiusSearch</a> (torch::Tensor <a class="el" href="io_2file__format_2_file_p_c_d_8cpp.375.delay#af7f8f4a4e39e09fdb5e9f02330ecabef">points</a>, torch::Tensor queries, torch::Tensor radii, torch::Tensor points_row_splits, torch::Tensor queries_row_splits, torch::ScalarType index_dtype, const std::string &amp;metric_str, const bool ignore_query_point, const bool return_distances, const bool normalize_distances)</td></tr>
<tr class="separator:ae6b0b2000f143e707c504b821f570dcc"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="var-members"></a>
Variables</h2></td></tr>
<tr class="memitem:a2b08a41baa3a1b3f07b8a8275c6a2f0c"><td class="memItemLeft" align="right" valign="top">const char *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="pytorch_2misc_2_radius_search_ops_8cpp.d06.d#a2b08a41baa3a1b3f07b8a8275c6a2f0c">radius_fn_format</a></td></tr>
<tr class="separator:a2b08a41baa3a1b3f07b8a8275c6a2f0c"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Macro Definition Documentation</h2>
<a id="a5bca80bb5cc651b5b0c11faceb94497f"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a5bca80bb5cc651b5b0c11faceb94497f">&#9670;&nbsp;</a></span>FN_PARAMETERS</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">#define FN_PARAMETERS</td>
        </tr>
      </table>
</div><div class="memdoc">
<b>Value:</b><div class="fragment"><div class="line">    <a class="code" href="io_2file__format_2_file_p_c_d_8cpp.375.delay#af7f8f4a4e39e09fdb5e9f02330ecabef">points</a>, queries, radii, points_row_splits, queries_row_splits, metric, \</div>
<div class="line">            ignore_query_point, return_distances, normalize_distances,     \</div>
<div class="line">            neighbors_index, neighbors_row_splits, neighbors_distance</div>
<div class="ttc" id="aio_2file__format_2_file_p_c_d_8cpp_html_af7f8f4a4e39e09fdb5e9f02330ecabef"><div class="ttname"><a href="io_2file__format_2_file_p_c_d_8cpp.375.delay#af7f8f4a4e39e09fdb5e9f02330ecabef">points</a></div><div class="ttdeci">int points</div><div class="ttdef"><b>Definition:</b> FilePCD.cpp:54</div></div>
</div><!-- fragment -->
</div>
</div>
<h2 class="groupheader">Function Documentation</h2>
<a id="ae6b0b2000f143e707c504b821f570dcc"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae6b0b2000f143e707c504b821f570dcc">&#9670;&nbsp;</a></span>MultiRadiusSearch()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">std::tuple&lt;torch::Tensor, torch::Tensor, torch::Tensor&gt; MultiRadiusSearch </td>
          <td>(</td>
          <td class="paramtype">torch::Tensor&#160;</td>
          <td class="paramname"><em>points</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">torch::Tensor&#160;</td>
          <td class="paramname"><em>queries</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">torch::Tensor&#160;</td>
          <td class="paramname"><em>radii</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">torch::Tensor&#160;</td>
          <td class="paramname"><em>points_row_splits</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">torch::Tensor&#160;</td>
          <td class="paramname"><em>queries_row_splits</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">torch::ScalarType&#160;</td>
          <td class="paramname"><em>index_dtype</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const std::string &amp;&#160;</td>
          <td class="paramname"><em>metric_str</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const bool&#160;</td>
          <td class="paramname"><em>ignore_query_point</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const bool&#160;</td>
          <td class="paramname"><em>return_distances</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const bool&#160;</td>
          <td class="paramname"><em>normalize_distances</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a5c53ee008516ea096adece570b14458e"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a5c53ee008516ea096adece570b14458e">&#9670;&nbsp;</a></span>RadiusSearchCPU()</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template&lt;class T , class TIndex &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">void RadiusSearchCPU </td>
          <td>(</td>
          <td class="paramtype">const torch::Tensor &amp;&#160;</td>
          <td class="paramname"><em>points</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const torch::Tensor &amp;&#160;</td>
          <td class="paramname"><em>queries</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const torch::Tensor &amp;&#160;</td>
          <td class="paramname"><em>radii</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const torch::Tensor &amp;&#160;</td>
          <td class="paramname"><em>points_row_splits</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const torch::Tensor &amp;&#160;</td>
          <td class="paramname"><em>queries_row_splits</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const <a class="el" href="namespaceopen3d_1_1core_1_1nns.html#a1ee06f6e576842e4122fded5bab8b074">Metric</a>&#160;</td>
          <td class="paramname"><em>metric</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const bool&#160;</td>
          <td class="paramname"><em>ignore_query_point</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const bool&#160;</td>
          <td class="paramname"><em>return_distances</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const bool&#160;</td>
          <td class="paramname"><em>normalize_distances</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">torch::Tensor &amp;&#160;</td>
          <td class="paramname"><em>neighbors_index</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">torch::Tensor &amp;&#160;</td>
          <td class="paramname"><em>neighbors_row_splits</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">torch::Tensor &amp;&#160;</td>
          <td class="paramname"><em>neighbors_distance</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<h2 class="groupheader">Variable Documentation</h2>
<a id="a2b08a41baa3a1b3f07b8a8275c6a2f0c"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a2b08a41baa3a1b3f07b8a8275c6a2f0c">&#9670;&nbsp;</a></span>radius_fn_format</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">const char* radius_fn_format</td>
        </tr>
      </table>
</div><div class="memdoc">
<b>Initial value:</b><div class="fragment"><div class="line">=</div>
<div class="line">        <span class="stringliteral">&quot;open3d::radius_search(Tensor points, Tensor queries, Tensor radii, &quot;</span></div>
<div class="line">        <span class="stringliteral">&quot;Tensor points_row_splits, Tensor queries_row_splits, ScalarType &quot;</span></div>
<div class="line">        <span class="stringliteral">&quot;index_dtype=%d,&quot;</span></div>
<div class="line">        <span class="stringliteral">&quot;str metric=\&quot;L2\&quot;, bool ignore_query_point=False, bool &quot;</span></div>
<div class="line">        <span class="stringliteral">&quot;return_distances=False, bool normalize_distances=False) -&gt; (Tensor &quot;</span></div>
<div class="line">        <span class="stringliteral">&quot;neighbors_index, Tensor &quot;</span></div>
<div class="line">        <span class="stringliteral">&quot;neighbors_row_splits, Tensor neighbors_distance)&quot;</span></div>
</div><!-- fragment -->
</div>
</div>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>

<!-- Mirrored from www.open3d.org/docs/release/cpp_api/pytorch_2misc_2_radius_search_ops_8cpp.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 14 May 2023 11:04:58 GMT -->
</html>
