<!-- HTML header for doxygen 1.8.20-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<!-- Mirrored from www.open3d.org/docs/release/cpp_api/t_2geometry_2kernel_2_point_cloud_8cpp.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 14 May 2023 11:04:38 GMT -->
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Open3D (C++ API): /home/runner/work/Open3D/Open3D/cpp/open3d/t/geometry/kernel/PointCloud.cpp File Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    extensions: ["tex2jax.js", "TeX/AMSmath.html", "TeX/AMSsymbols.js"],
    jax: ["input/TeX","output/HTML-CSS"],
});
</script>
<script type="text/javascript" async="async" src="../../../../cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-3TQPKGV6Z3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-3TQPKGV6Z3');
</script>
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectlogo"><img alt="Logo" src="open3d_logo.ico"/></td>
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">Open3D (C++ API)
   &#160;<span id="projectnumber">0.17.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.html');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.html','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_df511e5bd85cec96854b39d5e1c27aa8.357.del">cpp</a></li><li class="navelem"><a class="el" href="dir_f8cc15b2217ff526bd336cf17635da2a.358.del">open3d</a></li><li class="navelem"><a class="el" href="dir_98b8f8b2b857e52342ae5921735ee8da.359.del">t</a></li><li class="navelem"><a class="el" href="dir_9ad3ed4d28bdf7f9ee13f75fafbf67e8.4e2.del">geometry</a></li><li class="navelem"><a class="el" href="dir_32e7ebc243b57093c61a50ddd78d5309.96d.del">kernel</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#namespaces">Namespaces</a> &#124;
<a href="#func-members">Functions</a>  </div>
  <div class="headertitle">
<div class="title">PointCloud.cpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<h3 class="version">(9238339 (Tue Mar 14 18:49:09 2023 -0700))</h3><div class="textblock"><code>#include &quot;<a class="el" href="t_2geometry_2kernel_2_point_cloud_8h_source">open3d/t/geometry/kernel/PointCloud.h</a>&quot;</code><br />
<code>#include &lt;vector&gt;</code><br />
<code>#include &quot;<a class="el" href="_c_u_d_a_utils_8h_source.html">open3d/core/CUDAUtils.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="_shape_util_8h_source.html">open3d/core/ShapeUtil.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="_tensor_8h_source.html">open3d/core/Tensor.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="_logging_8h_source.html">open3d/utility/Logging.h</a>&quot;</code><br />
</div><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:namespaceopen3d"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceopen3d.html">open3d</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:namespaceopen3d_1_1t"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceopen3d_1_1t.html">open3d::t</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:namespaceopen3d_1_1t_1_1geometry"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceopen3d_1_1t_1_1geometry.html">open3d::t::geometry</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:namespaceopen3d_1_1t_1_1geometry_1_1kernel"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceopen3d_1_1t_1_1geometry_1_1kernel.4">open3d::t::geometry::kernel</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:namespaceopen3d_1_1t_1_1geometry_1_1kernel_1_1pointcloud"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceopen3d_1_1t_1_1geometry_1_1kernel_1-3">open3d::t::geometry::kernel::pointcloud</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a8b60362dce76067d7947d3a67fe757aa"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceopen3d_1_1t_1_1geometry_1_1kernel_1-3#a8b60362dce76067d7947d3a67fe757aa">open3d::t::geometry::kernel::pointcloud::Unproject</a> (const core::Tensor &amp;depth, utility::optional&lt; std::reference_wrapper&lt; const core::Tensor &gt;&gt; image_colors, core::Tensor &amp;<a class="el" href="io_2file__format_2_file_p_c_d_8cpp.375.delay#af7f8f4a4e39e09fdb5e9f02330ecabef">points</a>, utility::optional&lt; std::reference_wrapper&lt; core::Tensor &gt;&gt; colors, const core::Tensor &amp;intrinsics, const core::Tensor &amp;extrinsics, float depth_scale, float depth_max, int64_t <a class="el" href="_triangle_mesh_buffers_8cpp.html#a3f19cd85df5258a38e4618a89bd5ff46">stride</a>)</td></tr>
<tr class="separator:a8b60362dce76067d7947d3a67fe757aa"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa8ad1f9ee80aaadc25175d8b4c187a74"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceopen3d_1_1t_1_1geometry_1_1kernel_1-3#aa8ad1f9ee80aaadc25175d8b4c187a74">open3d::t::geometry::kernel::pointcloud::Project</a> (core::Tensor &amp;depth, utility::optional&lt; std::reference_wrapper&lt; core::Tensor &gt;&gt; image_colors, const core::Tensor &amp;<a class="el" href="io_2file__format_2_file_p_c_d_8cpp.375.delay#af7f8f4a4e39e09fdb5e9f02330ecabef">points</a>, utility::optional&lt; std::reference_wrapper&lt; const core::Tensor &gt;&gt; colors, const core::Tensor &amp;intrinsics, const core::Tensor &amp;extrinsics, float depth_scale, float depth_max)</td></tr>
<tr class="separator:aa8ad1f9ee80aaadc25175d8b4c187a74"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a166fe3f736d5e0c39370f3a787c92823"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceopen3d_1_1t_1_1geometry_1_1kernel_1-3#a166fe3f736d5e0c39370f3a787c92823">open3d::t::geometry::kernel::pointcloud::GetPointMaskWithinAABB</a> (const core::Tensor &amp;<a class="el" href="io_2file__format_2_file_p_c_d_8cpp.375.delay#af7f8f4a4e39e09fdb5e9f02330ecabef">points</a>, const core::Tensor &amp;min_bound, const core::Tensor &amp;max_bound, core::Tensor &amp;mask)</td></tr>
<tr class="separator:a166fe3f736d5e0c39370f3a787c92823"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aaefce435467df18716fe4fd2a7cc7453"><td class="memItemLeft" align="right" valign="top">void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceopen3d_1_1t_1_1geometry_1_1kernel_1-3#aaefce435467df18716fe4fd2a7cc7453">open3d::t::geometry::kernel::pointcloud::GetPointMaskWithinOBB</a> (const core::Tensor &amp;<a class="el" href="io_2file__format_2_file_p_c_d_8cpp.375.delay#af7f8f4a4e39e09fdb5e9f02330ecabef">points</a>, const core::Tensor &amp;center, const core::Tensor &amp;rotation, const core::Tensor &amp;extent, core::Tensor &amp;mask)</td></tr>
<tr class="separator:aaefce435467df18716fe4fd2a7cc7453"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>

<!-- Mirrored from www.open3d.org/docs/release/cpp_api/t_2geometry_2kernel_2_point_cloud_8cpp.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 14 May 2023 11:04:38 GMT -->
</html>
